import { useEffect, useRef, useState } from 'react';
import { createWorker } from 'tesseract.js';
import { api, SESSION_EXPIRED_EVENT, MAINTENANCE_EVENT, invalidateRequests } from './api';
import { watchSessionExpiry } from './session';
import { MemberOverview, HistoryPage } from './MemberPages';
import ChatWidget from './ChatWidget';
import DetectorPage from './DetectorPage';
import RecoveryPage from './RecoveryPage';
import ProfilePage from './ProfilePage';
import { ManagementSidebar } from './ManagementUI';
import { AdminOverview, AdminAnalysis, AdminReports, UserManagement, AuditLogPage, AdminSupport, AccountDetails, CyberDashboard } from './ManagementPages';
import { StaffOverview, ContentManager, MaintenancePage, MaintenanceScreen, PublishedContent } from './OperationsPages';

function passwordIssue(value) { return value.length < 8 || value.length > 128 || /\s/.test(value) ? 'Use 8–128 characters without spaces.' : ''; }

function Brand({ onClick }) { return <button className="brand" onClick={onClick}><span className="brand-mark">◈</span><span className="brand-copy">SCAMSCAN<em>PH · EXPLAINABLE RISK CHECKS</em></span></button>; }
function RiskBadge({ level }) { return <span className={'risk-badge ' + String(level).toLowerCase()}>{level}</span>; }
function Empty({ children }) { return <p className="empty">{children}</p>; }
function Banner({ banner, onClose }) { return <div className={'notice ' + banner.kind}><span>{banner.text}</span>{onClose && <button onClick={onClose}>×</button>}</div>; }
function PageTitle({ title, action }) { return <><h1 className="visually-hidden">{title}</h1>{action}</>; }

function AuthCard({ title, subtitle, children, goHome }) { return <section className="auth-page"><div className="auth-layout"><div className="auth-card"><Brand onClick={goHome} /><span className="eyebrow"><i /> SECURE ACCOUNT ACCESS</span><h1>{title}</h1><p>{subtitle}</p>{children}</div><aside className="auth-aside"><span className="eyebrow"><i /> SCAMSCAN PH</span><h2>One careful check can change what happens next.</h2><p>Understand suspicious messages, review the signals behind a risk score, and keep your checks in one private workspace.</p><div><span>01</span> Verify your email<span>02</span> Check suspicious content<span>03</span> Decide with confidence</div></aside></div></section>; }
function PasswordRules({ value }) { return <div className="password-rules" aria-live="polite"><span className={value.length >= 8 && value.length <= 128 ? 'met' : ''}>8–128 characters</span><span className={!/\s/.test(value) ? 'met' : ''}>No spaces</span></div>; }
function PasswordField({ label, name, autoComplete = 'current-password', required = true, minLength, onValueChange }) { const [visible, setVisible] = useState(false); return <label>{label}<span className="password-input"><input name={name} type={visible ? 'text' : 'password'} autoComplete={autoComplete} required={required} minLength={minLength} maxLength="128" onChange={(e) => onValueChange?.(e.target.value)} /><button type="button" aria-label={visible ? 'Hide password' : 'Show password'} title={visible ? 'Hide password' : 'Show password'} onClick={() => setVisible(!visible)}><svg viewBox="0 0 24 24" width="19" height="19" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="M2 12s3.6-6 10-6 10 6 10 6-3.6 6-10 6S2 12 2 12Z"/><circle cx="12" cy="12" r="2.5"/>{!visible && <path d="M3 21 21 3"/>}</svg></button></span></label>; }

function Landing({ go }) { return <section className="landing clean-landing"><div className="hero-copy"><span className="eyebrow"><i />EXPLAINABLE SCAM RISK CHECKS</span><h1>Think first.<br /><b>Scan smarter.</b></h1><p>ScamScan helps you recognize suspicious messages, links, and screenshots before you take action. Create your verified account to save reports and get private support.</p><div className="hero-actions"><button className="primary large-button" onClick={() => go('register')}>Create account</button><button className="secondary large-button" onClick={() => go('login')}>Sign in</button></div><p className="landing-note">Your reports stay in your account. Scores are guidance, not proof of fraud.</p></div><aside className="landing-preview"><div className="preview-top"><span className="status-dot" /> EXAMPLE RISK CHECK</div><div className="preview-score"><b>82</b><span>HIGH RISK</span></div><div className="preview-copy"><span>Signals detected</span><p>OTP request · urgent prize · shortened link</p></div><div className="preview-line"><i /><i /><i /></div><small>Explainable results · private history · recovery guidance</small></aside><div className="landing-features"><article><span>01</span><h2>Scan</h2><p>Check message text, URLs, and image screenshots for common scam signals.</p></article><article><span>02</span><h2>Understand</h2><p>See clear risk scores, matched indicators, and recommended next actions.</p></article><article><span>03</span><h2>Respond</h2><p>Keep private reports and access recovery guidance when something goes wrong.</p></article></div></section>; }
function ReportDetail({ report, back, backLabel = 'Back to Scan History' }) { const signals = report.signals?.length ? report.signals : report.flags.map((label) => ({ label, points: 0 })); const max = Math.max(...signals.map((signal) => signal.points), 1); return <section><PageTitle tag="SAVED REPORT" title="Scan report details">Saved {new Date(report.createdAt).toLocaleString()}</PageTitle><button className="secondary page-action" onClick={back}>← {backLabel}</button><div className="report-summary"><article className="score-panel"><div className="score-orb"><b>{report.score}</b><span>/ 100</span></div><div><span className="label">RISK CLASSIFICATION</span><h2>{report.level} risk</h2><p>{report.explanation}</p><RiskBadge level={report.level} /></div></article><article className="panel report-stats"><div><span>Language</span><b>{report.language}</b></div><div><span>Signals found</span><b>{report.flags.length}</b></div><div><span>Report date</span><b>{new Date(report.createdAt).toLocaleDateString()}</b></div></article><article className="panel"><span className="label">SUBMITTED CONTENT</span><p className="report-message">{report.message}</p></article><article className="panel"><span className="label">ANALYSIS BREAKDOWN</span><div className="signal-breakdown">{signals.map((signal) => <div key={signal.label}><div><span>{signal.label}</span><b>{signal.points ? '+' + signal.points : 'Detected'}</b></div><i style={{ width: ((signal.points / max) * 100) + '%' }} /></div>)}</div></article><article className="panel action-panel"><span className="label">RECOMMENDED ACTION</span><p>{report.recommendation}</p></article></div></section>; }
function SettingsPage({ user, savePreferences, changePassword, busy }) { return <section><PageTitle tag="ACCOUNT SETTINGS" title="Security and preferences">Control your ScamScan experience and keep your account secure.</PageTitle><div className="two-col"><form className="panel stack-form" onSubmit={savePreferences}><h2>Notifications</h2><label className="toggle-row"><span><b>Email notifications</b><small>Receive account and safety updates.</small></span><input name="emailNotifications" type="checkbox" defaultChecked={user.preferences?.emailNotifications} /></label><label className="toggle-row"><span><b>Scan safety tips</b><small>Show recommendations after every result.</small></span><input name="scanTips" type="checkbox" defaultChecked={user.preferences?.scanTips} /></label><button className="primary" disabled={busy}>{busy ? 'Saving…' : 'Save preferences'}</button></form><form className="panel stack-form" onSubmit={changePassword}><h2>Change password</h2><PasswordField label="Current password" name="currentPassword" /><PasswordField label="New password" name="newPassword" autoComplete="new-password" minLength="8" /><small>8–128 characters with no spaces.</small><PasswordField label="Confirm new password" name="confirmPassword" autoComplete="new-password" minLength="8" /><button className="secondary" disabled={busy}>{busy ? 'Updating…' : 'Change password'}</button></form></div></section>; }
function AboutPage() { return <section className="about-page"><PageTitle tag="ABOUT SCAMSCAN" title="A safer digital Philippines starts with a pause.">ScamScan is an educational capstone application for understanding scam signals and practicing safe response decisions.</PageTitle><div className="two-col"><article className="panel"><h2>Our mission</h2><p>Make scam awareness simple, explainable, and accessible for English, Tagalog, and Taglish messages.</p></article><article className="panel"><h2>How it works</h2><p>ScamScan checks visible scam patterns such as urgency, financial requests, OTP requests, suspicious links, prizes, and impersonation language.</p></article><article className="panel"><h2>Your privacy</h2><p>Your saved analyses belong to your user account. Avoid submitting OTPs, passwords, card numbers, account numbers, or other sensitive data.</p></article><article className="panel"><h2>Important limitation</h2><p>A result is a risk indicator, not proof. Verify through official apps, websites, or known support numbers before taking action.</p></article></div></section>; }

function EventForm({ event, setEvent, busy, submit }) { const inputs = [['isNewDevice', 'New device'], ['isUnknownIp', 'Unknown IP'], ['isUnusualTime', 'Unusual login time'], ['restrictedFolder', 'Restricted folder accessed'], ['portScan', 'Port-scan signs'], ['unusualTraffic', 'Unusual traffic volume']]; return <form className="event-form panel" onSubmit={submit}><div className="field-grid"><label>Activity type<select value={event.type} onChange={(e) => setEvent({ ...event, type: e.target.value })}><option value="login">Login activity</option><option value="file">File activity</option><option value="network">Network activity</option><option value="behavior">User behavior</option></select></label><label>User / actor<input value={event.actor} onChange={(e) => setEvent({ ...event, actor: e.target.value })} required /></label><label>Observed at<input type="datetime-local" value={event.occurredAt} onChange={(e) => setEvent({ ...event, occurredAt: e.target.value })} /></label><label>IP address<input value={event.ip} onChange={(e) => setEvent({ ...event, ip: e.target.value })} /></label><label>Device<input value={event.device} onChange={(e) => setEvent({ ...event, device: e.target.value })} /></label><label>Location<input value={event.location} onChange={(e) => setEvent({ ...event, location: e.target.value })} /></label><label>Failed attempts<input type="number" min="0" value={event.failedAttempts} onChange={(e) => setEvent({ ...event, failedAttempts: e.target.value })} /></label><label>Files affected<input type="number" min="0" value={event.fileCount} onChange={(e) => setEvent({ ...event, fileCount: e.target.value })} /></label></div><fieldset><legend>Risk indicators</legend>{inputs.map(([key, label]) => <label className="checkbox" key={key}><input type="checkbox" checked={event[key]} onChange={(e) => setEvent({ ...event, [key]: e.target.checked })} />{label}</label>)}</fieldset><button className="primary" disabled={busy}>{busy ? 'Creating…' : 'Score and save event'}</button></form>; }
function AdminReportEditor({ report, save, busy }) { return <form className="panel stack-form admin-report-editor" onSubmit={save} key={report._id}><span className="label">HUMAN REVIEW</span><h2>Edit this assessment</h2><p>Changes update the saved report. The original detected signals remain visible, and your review is recorded in the audit log.</p><div className="field-grid"><label>Risk score<input type="number" name="score" min="0" max="100" defaultValue={report.score} required /></label><label>Risk level<select name="level" defaultValue={report.level}><option>Safe</option><option>Warning</option><option>High</option><option>Scam</option></select></label></div><label>Explanation<textarea name="explanation" minLength="10" maxLength="1000" defaultValue={report.explanation} required /></label><label>Recommendation<textarea name="recommendation" minLength="10" maxLength="1000" defaultValue={report.recommendation} required /></label><label>Review note<textarea name="note" maxLength="500" defaultValue={report.adminReview?.note || ''} placeholder="Why did you change this assessment?" /></label><button className="primary" disabled={busy}>{busy ? 'Saving review…' : 'Save reviewed report'}</button></form>; }
export default function App() {
  const [page, setPage] = useState('home');
  const [user, setUser] = useState(null);
  const [sessionExpiresAt, setSessionExpiresAt] = useState(null);
  const [checkingSession, setCheckingSession] = useState(true);
  const [busy, setBusy] = useState(false);
  const [chatOpen, setChatOpen] = useState(false);
  const [scanMode, setScanMode] = useState('text');
  const [message, setMessage] = useState('');
  const [imageFile, setImageFile] = useState(null);
  const [ocrProgress, setOcrProgress] = useState(0);
  const [analysis, setAnalysis] = useState(null);
  const [history, setHistory] = useState([]);
  const [historyLoading, setHistoryLoading] = useState(false);
  const [scanTotal, setScanTotal] = useState(0);
  const [historyTotal, setHistoryTotal] = useState(0);
  const [historyPage, setHistoryPage] = useState(1);
  const [historyPages, setHistoryPages] = useState(1);
  const [historyLevel, setHistoryLevel] = useState('All');
  const [selectedReport, setSelectedReport] = useState(null);
  const [dashboard, setDashboard] = useState(null);
  const [analytics, setAnalytics] = useState(null);
  const [users, setUsers] = useState([]);
  const [banner, setBanner] = useState(null);
  const [forgotResult, setForgotResult] = useState(null);
  const [pendingEmail, setPendingEmail] = useState('');
  const [verificationCode, setVerificationCode] = useState('');
  const [pendingDevOtp, setPendingDevOtp] = useState('');
  const [adminOverview, setAdminOverview] = useState(null);
  const [adminReports, setAdminReports] = useState([]);
  const [adminReportsLoading, setAdminReportsLoading] = useState(false);
  const [adminReportTotal, setAdminReportTotal] = useState(0);
  const [adminReportPage, setAdminReportPage] = useState(1);
  const [adminReportPages, setAdminReportPages] = useState(1);
  const [adminReportLevel, setAdminReportLevel] = useState('All');
  const [auditLogs, setAuditLogs] = useState([]);
  const [supportInbox, setSupportInbox] = useState([]);
  const [mySupport, setMySupport] = useState([]);
  const [accountDetails, setAccountDetails] = useState(null);
  const [loginCooldown, setLoginCooldown] = useState(0);
  const [registrationPassword, setRegistrationPassword] = useState('');
  const accountRef = useRef(null);
  const historyRequestRef = useRef(0);
  const adminReportRequestRef = useRef(0);
  const mySupportRequestRef = useRef(0);
  const supportInboxRequestRef = useRef(0);
  const [event, setEvent] = useState({ type: 'login', actor: 'j.delacruz', ip: '185.220.101.8', device: 'Unknown Windows device', location: 'Unknown', occurredAt: new Date().toISOString().slice(0, 16), failedAttempts: 12, isNewDevice: true, isUnknownIp: true, isUnusualTime: true, fileCount: 0, restrictedFolder: false, portScan: false, unusualTraffic: false });
  const isAdmin = user?.role === 'admin';
  const isStaff = user?.role === 'staff';
  const isManager = isAdmin || isStaff;
  const [staffOverview, setStaffOverview] = useState(null);
  const [siteStatus, setSiteStatus] = useState({ maintenanceEnabled: false, maintenanceMessage: '' });
  const [publishedContent, setPublishedContent] = useState([]);
  const workspaceHome = (account) => account?.role === 'admin' ? 'adminOverview' : account?.role === 'staff' ? 'staffOverview' : 'home';
  const go = (next) => { setBanner(null); if (next === 'chat') { setChatOpen(true); return; } setPage(next); };
  const error = (text) => setBanner({ kind: 'error', text });
  const success = (text) => setBanner({ kind: 'success', text });
  function expireSession(message = 'Your session has expired. Please sign in again.') { accountRef.current = null; invalidateRequests(); setUser(null); setSessionExpiresAt(null); setBusy(false); setPage('login'); setBanner({ kind: 'error', text: message }); }
  function acceptSession(result) { invalidateRequests(); setUser(result.user); setSessionExpiresAt(result.sessionExpiresAt || null); go(workspaceHome(result.user)); }
  async function refreshSiteStatus() { try { const status = await api.getSiteStatus(); setSiteStatus(status); } catch { /* Retain the last known maintenance state during a connection problem. */ } }
  async function loadPublishedContent() { try { const result = await api.getPublishedContent(); setPublishedContent(result.contents); } catch { setPublishedContent([]); } }
  useEffect(() => { let active = true; api.getMe().then((result) => { if (active) { setUser(result.user); setSessionExpiresAt(result.sessionExpiresAt || null); setPage(workspaceHome(result.user)); } }).catch((error) => { if (active) { setUser(null); setSessionExpiresAt(null); if (error.code === 'MAINTENANCE_MODE') { setSiteStatus({ maintenanceEnabled: true, maintenanceMessage: error.message }); setPage('maintenance'); } } }).finally(() => { if (active) setCheckingSession(false); }); return () => { active = false; }; }, []);
  useEffect(() => { const handleExpiredSession = (event) => expireSession(event.detail?.message); const handleMaintenance = (event) => { setSiteStatus({ maintenanceEnabled: true, maintenanceMessage: event.detail?.message }); setPage((current) => ['login', 'forgot', 'reset'].includes(current) ? current : 'maintenance'); }; window.addEventListener(SESSION_EXPIRED_EVENT, handleExpiredSession); window.addEventListener(MAINTENANCE_EVENT, handleMaintenance); return () => { window.removeEventListener(SESSION_EXPIRED_EVENT, handleExpiredSession); window.removeEventListener(MAINTENANCE_EVENT, handleMaintenance); }; }, []);
  useEffect(() => { refreshSiteStatus(); const timer = setInterval(refreshSiteStatus, 30000); window.addEventListener('focus', refreshSiteStatus); return () => { clearInterval(timer); window.removeEventListener('focus', refreshSiteStatus); }; }, []);
  useEffect(() => { if (siteStatus.maintenanceEnabled && !isAdmin) { setPage((current) => ['login', 'forgot', 'reset'].includes(current) ? current : 'maintenance'); } else { setPage((current) => !isAdmin && current === 'maintenance' ? workspaceHome(user) : current); loadPublishedContent(); } }, [siteStatus.maintenanceEnabled, isAdmin]);

  useEffect(() => {
    if (!user || !sessionExpiresAt) return undefined;
    return watchSessionExpiry(sessionExpiresAt, () => expireSession());
  }, [user?.id, sessionExpiresAt]);
  useEffect(() => { accountRef.current = user?.id || null; setChatOpen(false); setMessage(''); setImageFile(null); setAnalysis(null); setOcrProgress(0); setScanMode('text'); setHistory([]); setHistoryLoading(false); setHistoryPage(1); setHistoryLevel('All'); setHistoryTotal(0); setScanTotal(0); setMySupport([]); setSelectedReport(null); setAccountDetails(null); setAdminReports([]); setAdminReportsLoading(false); setAdminReportPage(1); setAdminReportLevel('All'); setAdminOverview(null); setStaffOverview(null); setUsers([]); setSupportInbox([]); setAuditLogs([]); setDashboard(null); setAnalytics(null); }, [user?.id]);
  useEffect(() => { if (!loginCooldown) return; const timer = setInterval(() => setLoginCooldown((seconds) => Math.max(0, seconds - 1)), 1000); return () => clearInterval(timer); }, [loginCooldown > 0]);
  useEffect(() => { if (!user || (siteStatus.maintenanceEnabled && !isAdmin)) return; if (page === 'history') loadHistory(); if (['home', 'profile'].includes(page) && !isManager) loadScanTotal(); if (page === 'help') loadMySupport(); if (page === 'adminOverview' && isAdmin) loadAdminOverview(); if (page === 'staffOverview' && isStaff) loadStaffOverview(); if (page === 'adminAnalytics' && isAdmin) loadAnalytics(); if (page === 'adminCyber' && isAdmin) loadDashboard(); if (page === 'adminUsers' && isManager) loadUsers(); if (page === 'adminReports' && isAdmin) loadAdminReports(); if (page === 'adminAudit' && isAdmin) loadAuditLogs(); if (page === 'adminSupport' && isManager) loadSupportInbox(); }, [page, user?.id, user?.role, siteStatus.maintenanceEnabled, historyPage, historyLevel, adminReportPage, adminReportLevel]);
  async function run(task, minimumDelay = 450) { const account = accountRef.current; setBusy(true); setBanner(null); const started = Date.now(); try { const result = await task(); const remaining = minimumDelay - (Date.now() - started); if (remaining > 0) await new Promise((resolve) => setTimeout(resolve, remaining)); return account === accountRef.current ? result : null; } catch (e) { if (!e.sessionExpired && account === accountRef.current) { if (e.retryAfter) setLoginCooldown(e.retryAfter); error(e.message); } return null; } finally { setBusy(false); } }
  async function loadHistory() {
    const account = accountRef.current;
    const requestId = ++historyRequestRef.current;
    setHistoryLoading(true); setHistory([]);
    const result = await run(() => api.getScamHistory({ page: historyPage, level: historyLevel }), 0);
    if (account !== accountRef.current || requestId !== historyRequestRef.current) return;
    setHistoryLoading(false);
    if (result) { setHistory(result.analyses); setHistoryTotal(result.total); setHistoryPages(result.pages); setHistoryPage(result.page); setScanTotal((current) => historyLevel === 'All' ? result.total : current); }
  }
  async function loadScanTotal() { const account = accountRef.current; const result = await run(() => api.getScamHistory({ page: 1 }), 0); if (result && account === accountRef.current) setScanTotal(result.total); }
  async function loadAnalytics() { const account = accountRef.current; const result = await run(api.getScamAnalytics); if (result && account === accountRef.current) setAnalytics(result); }
  async function loadDashboard() { const account = accountRef.current; const result = await run(api.getThreatDashboard); if (result && account === accountRef.current) setDashboard(result); }
  async function loadUsers() { const account = accountRef.current; const result = await run(api.getUsers); if (result && account === accountRef.current) setUsers(result.users); }
  async function loadStaffOverview() { const result = await run(api.getStaffOverview, 0); if (result) setStaffOverview(result); }
  async function loadAdminOverview() { const account = accountRef.current; const result = await run(api.getAdminOverview); if (result && account === accountRef.current) setAdminOverview(result); }
  async function loadAdminReports() {
    const account = accountRef.current; const requestId = ++adminReportRequestRef.current;
    setAdminReportsLoading(true); setAdminReports([]);
    const result = await run(() => api.getAdminReports({ page: adminReportPage, level: adminReportLevel }), 0);
    if (account !== accountRef.current || requestId !== adminReportRequestRef.current) return;
    setAdminReportsLoading(false);
    if (result) { setAdminReports(result.reports); setAdminReportTotal(result.total); setAdminReportPages(result.pages); if (result.page > result.pages) setAdminReportPage(result.pages); }
  }
  async function loadAuditLogs() { const account = accountRef.current; const result = await run(api.getAuditLogs); if (result && account === accountRef.current) setAuditLogs(result.logs); }
  async function loadSupportInbox() { const account = accountRef.current; const requestId = ++supportInboxRequestRef.current; const result = await run(api.getAdminSupport); if (result && account === accountRef.current && requestId === supportInboxRequestRef.current) setSupportInbox(result.support); }
  async function loadMySupport() { const account = accountRef.current; const requestId = ++mySupportRequestRef.current; const result = await run(api.getMySupport); if (result && account === accountRef.current && requestId === mySupportRequestRef.current) setMySupport(result.support); }
  async function register(e) { e.preventDefault(); const data = Object.fromEntries(new FormData(e.currentTarget)); if (data.password !== data.confirmPassword) return error('The password confirmation does not match.'); const issue = passwordIssue(data.password); if (issue) return error(issue); const result = await run(() => api.register(data)); if (result) { setPendingEmail(result.email); setVerificationCode(''); setPendingDevOtp(result.devOtp || ''); go('verify'); success(result.message); } }
  async function verifyEmail(e) { e.preventDefault(); const data = new FormData(e.currentTarget); const email = data.get('email') || pendingEmail; const result = await run(() => api.verifyEmail(email, verificationCode)); if (result) { setPendingEmail(email); setVerificationCode(''); acceptSession(result); setPendingDevOtp(''); success('Email verified. Your ScamScan account is ready.'); } }
  async function resendVerification() { if (!pendingEmail) return error('Enter your email address first.'); const result = await run(() => api.resendVerification(pendingEmail)); if (result) { setPendingDevOtp(result.devOtp || ''); success(result.message); } }
  async function login(e) { e.preventDefault(); if (loginCooldown) return; const data = Object.fromEntries(new FormData(e.currentTarget)); const result = await run(() => api.login(data)); if (result) { acceptSession(result); setLoginCooldown(0); } }
  async function logout() { const result = await run(api.logout); if (result !== null) { invalidateRequests(); accountRef.current = null; setUser(null); setSessionExpiresAt(null); go('login'); } }
  async function forgot(e) { e.preventDefault(); const email = new FormData(e.currentTarget).get('email'); const result = await run(() => api.forgotPassword(email)); if (result) { setPendingEmail(email); setPendingDevOtp(result.devOtp || ''); setForgotResult(result); go('reset'); } }
  async function reset(e) { e.preventDefault(); const data = Object.fromEntries(new FormData(e.currentTarget)); if (data.password !== data.confirmPassword) return error('The password confirmation does not match.'); const issue = passwordIssue(data.password); if (issue) return error(issue); const result = await run(() => api.resetPassword(data.email, data.code, data.password)); if (result) { setPendingDevOtp(''); go('login'); success(result.message); } }
  async function analyze(e) { e.preventDefault(); const account = accountRef.current; const submitted = message.trim(); if (submitted.length < 10) return error('Enter at least 10 characters to check.'); const result = await run(() => api.analyzeMessage(submitted)); if (result && account === accountRef.current) { setAnalysis(result); setMessage(''); setScanTotal((count) => count + 1); success('Check complete. The input is clear for your next scan.'); } }
  async function analyzeImage() { const account = accountRef.current; if (!imageFile) return error('Choose an image before starting image detection.'); if (!['image/png', 'image/jpeg', 'image/webp'].includes(imageFile.type) || imageFile.size > 5 * 1024 * 1024) return error('Choose a PNG, JPG, or WEBP screenshot under 5 MB.'); const result = await run(async () => { const worker = await createWorker('eng', 1, { logger: (event) => { if (account === accountRef.current && event.status === 'recognizing text') setOcrProgress(Math.round((event.progress || 0) * 100)); } }); try { const response = await worker.recognize(imageFile); const extractedText = response.data.text.trim(); if (extractedText.length < 10) throw new Error('Not enough readable text was found. Try a clearer screenshot or paste its text.'); return api.analyzeMessage(extractedText); } finally { await worker.terminate(); } }, 650); if (result && account === accountRef.current) { setAnalysis(result); setMessage(''); setImageFile(null); setOcrProgress(0); setScanTotal((count) => count + 1); success('Screenshot checked and saved. The image input is clear for your next scan.'); } }
  async function deleteScan(id) { if (!window.confirm('Delete this saved scan?')) return; const result = await run(() => api.deleteScan(id)); if (result !== null) loadHistory(); }
  async function saveProfile(e) { e.preventDefault(); const result = await run(() => api.updateProfile(new FormData(e.currentTarget).get('name'))); if (result) { setUser(result.user); success('Profile saved.'); } }
  async function savePreferences(e) { e.preventDefault(); const data = new FormData(e.currentTarget); const result = await run(() => api.updatePreferences({ emailNotifications: data.get('emailNotifications') === 'on', scanTips: data.get('scanTips') === 'on' })); if (result) { setUser(result.user); success('Preferences saved.'); } }
  async function changePassword(e) { e.preventDefault(); const data = Object.fromEntries(new FormData(e.currentTarget)); if (data.newPassword !== data.confirmPassword) return error('The password confirmation does not match.'); const issue = passwordIssue(data.newPassword); if (issue) return error(issue); const result = await run(() => api.changePassword(data.currentPassword, data.newPassword)); if (result) { invalidateRequests(); accountRef.current = null; setUser(null); setSessionExpiresAt(null); go('login'); success(result.message); } }
  async function createEvent(e) { e.preventDefault(); const result = await run(() => api.createEvent({ ...event, failedAttempts: Number(event.failedAttempts), fileCount: Number(event.fileCount) })); if (result) { go('adminCyber'); loadDashboard(); } }
  async function seedDemo() { const result = await run(api.seedDemo); if (result) { go('adminCyber'); loadDashboard(); } }
  async function updateAlert(id, status) { const result = await run(() => api.updateAlertStatus(id, status)); if (result) loadDashboard(); }
  async function manageUser(id, data) { const result = await run(() => api.updateUser(id, data)); if (result) { success('User access updated.'); loadUsers(); } return Boolean(result); }
  async function removeUser(member) { if (!window.confirm('Permanently delete ' + member.email + ' and their saved data?')) return; const result = await run(() => api.deleteUser(member._id)); if (result !== null) { success('User and associated saved data deleted.'); loadUsers(); } }
  async function openAccountDetails(id) { const result = await run(() => api.getUserDetails(id)); if (result) { setAccountDetails(result); go('adminAccountDetails'); } }
  async function updateSupportStatus(id, status) { const result = await run(() => api.updateSupportStatus(id, status)); if (result) { success('Support status updated.'); loadSupportInbox(); } }
  async function sendHelp(e) { e.preventDefault(); const account = accountRef.current; const form = e.currentTarget; const data = new FormData(form); const result = await run(() => api.sendSupport(data.get('subject'), data.get('message'))); if (result && account === accountRef.current) { ++mySupportRequestRef.current; form.reset(); setMySupport((items) => [result.support, ...items]); success('Your request was saved and is visible below.'); } }
  async function replyToHelp(id, body, form) { const account = accountRef.current; const result = await run(() => api.replyToSupport(id, body)); if (result && account === accountRef.current) { ++supportInboxRequestRef.current; form.reset(); setSupportInbox((items) => items.map((item) => item._id === id ? result.support : item)); success(result.emailed ? 'Reply saved and emailed to the member.' : 'Reply saved. The member can read it in Help Center.'); } }
  async function saveAdminReport(e) { e.preventDefault(); const data = Object.fromEntries(new FormData(e.currentTarget)); const result = await run(() => api.updateAdminReport(selectedReport._id, data)); if (result) { setSelectedReport(result.report); setAdminReports((items) => items.map((item) => item._id === result.report._id ? result.report : item)); success('Reviewed report saved and logged.'); } }

  if (checkingSession) return <div className="loading-screen">Loading ScamScan…</div>;
  const authProps = { goHome: () => go(workspaceHome(user)) };
  if (((page === 'maintenance' && !isAdmin) || (siteStatus.maintenanceEnabled && !isAdmin && !['login', 'forgot', 'reset'].includes(page)))) return <MaintenanceScreen message={siteStatus.maintenanceMessage} go={go} refresh={refreshSiteStatus} />;
  if (page === 'login') return <AuthCard {...authProps} title="Welcome back" subtitle="Sign in to continue to your ScamScan workspace."><form className="stack-form" onSubmit={login}><label>Email address<input name="email" type="email" autoComplete="email" maxLength="254" required placeholder="you@example.com" /></label><PasswordField label="Password" name="password" /><button className="primary auth-action" disabled={busy || loginCooldown > 0}>{loginCooldown ? `Try again in ${Math.ceil(loginCooldown / 60)} min` : busy ? 'Signing in…' : 'Sign in securely'}</button></form>{loginCooldown > 0 && <p className="cooldown-note">Too many incorrect passwords. Wait {Math.ceil(loginCooldown / 60)} minute{loginCooldown > 60 ? 's' : ''}, then try again.</p>}<div className="auth-links"><button className="text-button center" onClick={() => go('forgot')}>Forgot password?</button><button className="text-button center" onClick={() => go('verify')}>Verify an email</button></div><p className="auth-switch">New here? <button className="inline-button" onClick={() => go('register')}>Create an account</button></p>{banner && <Banner banner={banner} />}</AuthCard>;
  if (page === 'register') return <AuthCard {...authProps} title="Create your account" subtitle="We send a code first. Your account is created only after you verify your email."><form className="stack-form" onSubmit={register}><label>Name<input name="name" minLength="2" maxLength="80" autoComplete="name" required placeholder="Your name" /></label><label>Email address<input name="email" type="email" maxLength="254" autoComplete="email" required placeholder="you@example.com" /></label><PasswordField label="Password" name="password" autoComplete="new-password" minLength="8" onValueChange={setRegistrationPassword} /><PasswordRules value={registrationPassword} /><PasswordField label="Confirm password" name="confirmPassword" autoComplete="new-password" minLength="8" /><button className="primary auth-action" disabled={busy}>{busy ? 'Sending verification code…' : 'Send verification code'}</button></form><p className="auth-switch">Already registered? <button className="inline-button" onClick={() => go('login')}>Sign in</button></p>{banner && <Banner banner={banner} />}</AuthCard>;
  if (page === 'verify') return <AuthCard {...authProps} title="Verify your email" subtitle={pendingEmail ? 'Enter the six-digit code sent to ' + pendingEmail + '. It expires in 10 minutes.' : 'Enter your email address and the six-digit verification code.'}><form className="stack-form" onSubmit={verifyEmail}><label>Email<input name="email" type="email" value={pendingEmail} autoComplete="email" onChange={(e) => setPendingEmail(e.target.value)} required /></label><label>Verification code<input name="code" type="text" value={verificationCode} inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6}" minLength="6" maxLength="6" placeholder="123456" onChange={(e) => setVerificationCode(e.target.value.replace(/\D/g, '').slice(0, 6))} required /></label><button className="primary" disabled={busy || verificationCode.length !== 6}>{busy ? 'Verifying…' : 'Verify & sign in'}</button></form>{pendingDevOtp && <div className="info-card"><b>Development-only code</b><p>{pendingDevOtp}</p><small>Configure SMTP in server/.env before deploying. This code is never returned in production.</small></div>}<button className="text-button center" disabled={busy} onClick={resendVerification}>Send a new code</button>{banner && <Banner banner={banner} />}</AuthCard>;
  if (page === 'forgot') return <AuthCard {...authProps} title="Reset password" subtitle="We will send a six-digit password-reset code to your verified account email."><form className="stack-form" onSubmit={forgot}><label>Email<input name="email" type="email" required /></label><button className="primary" disabled={busy}>{busy ? 'Sending…' : 'Send reset code'}</button></form><button className="text-button center" onClick={() => go('login')}>Back to sign in</button>{banner && <Banner banner={banner} />}</AuthCard>;
  if (page === 'reset') return <AuthCard {...authProps} title="Choose a new password" subtitle={'Enter the six-digit code sent to ' + pendingEmail + '.'}><form className="stack-form" onSubmit={reset}><label>Email<input name="email" type="email" defaultValue={pendingEmail} required /></label><label>Reset code<input name="code" inputMode="numeric" pattern="[0-9]{6}" maxLength="6" placeholder="123456" required /></label><PasswordField label="New password" name="password" autoComplete="new-password" minLength="8" /><small>8–128 characters with no spaces.</small><PasswordField label="Confirm password" name="confirmPassword" autoComplete="new-password" minLength="8" /><button className="primary" disabled={busy}>{busy ? 'Updating…' : 'Update password'}</button></form>{pendingDevOtp && <div className="info-card"><b>Development-only code</b><p>{pendingDevOtp}</p></div>}{forgotResult && <p className="auth-switch">{forgotResult.message}</p>}{banner && <Banner banner={banner} />}</AuthCard>;

  const userNav = [['home', 'Overview'], ['scanner', 'Detector'], ['history', 'Scan History'], ['chat', 'Chat with Staff'], ['help', 'Recovery Guide'], ['profile', 'Profile'], ['settings', 'Settings'], ['about', 'About Us']];
  const staffNav = [['staffOverview', 'Staff Overview'], ['adminUsers', 'Manage Users'], ['contents', 'Manage Content'], ['chat', 'Member Chat'], ['adminSupport', 'Customer Support'], ['profile', 'My Profile'], ['settings', 'Security Settings']];
  const adminNav = [['adminOverview', 'Control Center'], ['adminReports', 'Report Review'], ['chat', 'Support Chat'], ['adminSupport', 'Help Inbox'], ['adminUsers', 'Accounts'], ['adminAnalytics', 'System Analysis'], ['adminAudit', 'Audit Log'], ['adminCyber', 'CyberShield'], ['adminEvents', 'Simulate Event'], ['contents', 'Manage Content'], ['maintenance', 'Maintenance Mode'], ['profile', 'My Profile'], ['settings', 'Security Settings']];
  let content = user ? (isAdmin ? <AdminOverview data={adminOverview} go={go} refresh={loadAdminOverview} busy={busy} /> : isStaff ? <StaffOverview data={staffOverview} go={go} refresh={loadStaffOverview} busy={busy} /> : <><MemberOverview user={user} scanTotal={scanTotal} go={go} /><PublishedContent contents={publishedContent} /></>) : null;
  if (['contents', 'maintenance'].includes(page)) {
    if (page === 'contents' && isManager) content = <ContentManager key={user.id} run={run} onPublishedChange={loadPublishedContent} />;
    if (page === 'maintenance' && isAdmin) content = <MaintenancePage key={user.id} run={run} onChange={setSiteStatus} />;
  }
  if (page === 'scanner' && !isManager) content = <DetectorPage go={go} key={user.id} scanMode={scanMode} setScanMode={setScanMode} message={message} setMessage={setMessage} imageFile={imageFile} setImageFile={setImageFile} ocrProgress={ocrProgress} analyze={analyze} analyzeImage={analyzeImage} analysis={analysis} clearAnalysis={() => setAnalysis(null)} busy={busy} />;
  if (page === 'history' && !isManager) content = <HistoryPage loading={historyLoading} busy={busy} history={history} total={historyTotal} page={historyPage} pages={historyPages} level={historyLevel} setPage={setHistoryPage} setLevel={setHistoryLevel} openReport={(item) => { setSelectedReport(item); go('report'); }} deleteScan={deleteScan} />;
  if (page === 'report' && selectedReport) content = <><ReportDetail report={selectedReport} backLabel={isAdmin ? 'Back to reports' : isStaff ? 'Back to account record' : 'Back to Scan History'} back={() => go(isAdmin ? 'adminReports' : isStaff ? 'adminAccountDetails' : 'history')} />{isAdmin && <AdminReportEditor report={selectedReport} save={saveAdminReport} busy={busy} />}</>;
  if (page === 'profile' && user) content = <ProfilePage go={go} user={user} scanTotal={scanTotal} saveProfile={saveProfile} busy={busy} />;
  if (page === 'settings' && user) content = <SettingsPage user={user} savePreferences={savePreferences} changePassword={changePassword} busy={busy} />;
  if (page === 'help') content = <RecoveryPage go={go} sendHelp={sendHelp} busy={busy} mySupport={mySupport} />;
  if (page === 'about') content = <AboutPage />;
  if (page === 'adminAnalytics' && isAdmin) content = <AdminAnalysis analytics={analytics} refresh={loadAnalytics} busy={busy} />;
  if (page === 'adminCyber' && isAdmin) content = <CyberDashboard dashboard={dashboard} refresh={loadDashboard} updateAlert={updateAlert} busy={busy} />;
  if (page === 'adminEvents' && isAdmin) content = <section><PageTitle tag="ADMIN CONSOLE" title="Simulate a security event">Creates clearly labelled synthetic data in MongoDB; it never touches real networks or devices.</PageTitle><EventForm event={event} setEvent={setEvent} busy={busy} submit={createEvent} /><button className="secondary page-action" onClick={seedDemo} disabled={busy}>Load safe demo data</button></section>;
  if (page === 'adminReports' && isAdmin) content = <AdminReports loading={adminReportsLoading} busy={busy} reports={adminReports} total={adminReportTotal} page={adminReportPage} pages={adminReportPages} level={adminReportLevel} setPage={setAdminReportPage} setLevel={setAdminReportLevel} openReport={(report) => { setSelectedReport(report); go('report'); }} />;
  if (page === 'adminAudit' && isAdmin) content = <AuditLogPage key={user.id} logs={auditLogs} refresh={loadAuditLogs} busy={busy} loading={busy && !auditLogs.length} />;
  if (page === 'adminSupport' && isManager) content = <AdminSupport key={user.id} refresh={loadSupportInbox} loading={busy && !supportInbox.length} items={supportInbox} busy={busy} updateStatus={updateSupportStatus} replyToHelp={replyToHelp} />;
  if (page === 'adminUsers' && isManager) content = <UserManagement key={user.id} refresh={loadUsers} loading={busy && !users.length} currentUserId={user.id} users={users} busy={busy} onChange={manageUser} onDelete={removeUser} onDetails={openAccountDetails} allowRoles={isAdmin} />;
  if (page === 'adminAccountDetails' && isManager) content = <AccountDetails key={accountDetails?.user?.id || user.id} admin={isAdmin} details={accountDetails} back={() => go('adminUsers')} openReport={(report) => { setSelectedReport(report); go('report'); }} />;
  const visibleNav = isAdmin ? adminNav : isStaff ? staffNav : userNav;
  return <div className={'app-shell' + (isManager ? ' management-shell' : '')}><div className="grid-bg" /><header className="topbar"><Brand onClick={() => go(workspaceHome(user))} />{user && <div className="header-status"><span className="status-dot" /> ENGINE ONLINE</div>}{user ? <div className="account-menu"><button onClick={() => go('profile')}><b>{user.name}</b><small>{isAdmin ? 'ADMIN' : isStaff ? 'STAFF' : 'MEMBER'}</small></button><button className="signout" disabled={busy} onClick={logout}>{busy ? 'Signing out…' : 'Sign out'}</button></div> : <div className="header-actions"><button className="text-button" onClick={() => go('login')}>Sign in</button><button className="primary" onClick={() => go('register')}>Create account</button></div>}</header>{user ? <div className="layout">{isManager ? <ManagementSidebar entries={visibleNav} page={page} chatOpen={chatOpen} go={go} role={user.role} /> : <aside className="sidebar"><span className="side-label">{isAdmin ? 'ADMIN ACCESS' : isStaff ? 'STAFF ACCESS' : 'MEMBER ACCESS'}</span>{visibleNav.map(([id, label]) => <button className={page === id || (id === 'chat' && chatOpen) ? 'active' : ''} key={id} onClick={() => go(id)}>{label}</button>)}</aside>}<main className="content">{isAdmin && siteStatus.maintenanceEnabled && <div className="maintenance-status">Maintenance is enabled. User and staff access is paused. <button className="inline-button" onClick={() => go('maintenance')}>Manage mode</button></div>}{banner && <Banner banner={banner} onClose={() => setBanner(null)} />}{content}</main></div> : <main className="landing-content">{banner && <Banner banner={banner} onClose={() => setBanner(null)} />}{<><Landing go={go} /><PublishedContent contents={publishedContent} /></>}</main>}{user && <ChatWidget key={user.id + ':' + user.role} user={user} open={chatOpen} setOpen={setChatOpen} />}</div>;
}
