import { useEffect, useRef, useState } from 'react';
import { createWorker } from 'tesseract.js';
import { api } from './api';

const SAMPLE_SCAM = 'Congratulations! Nanalo ka ng ₱50,000. Send your OTP and click bit.ly/claim-now to claim your prize today.';
const riskTabs = ['All', 'Scam', 'High', 'Warning', 'Safe'];
function passwordIssue(value) { return value.length < 8 || value.length > 128 || /\s/.test(value) || !/[A-Za-z]/.test(value) || !/\d/.test(value) ? 'Use 8–128 characters with a letter and a number, without spaces.' : ''; }
const playbooks = [
  ['I shared my bank OTP or PIN', ['Call your bank’s fraud hotline immediately and ask them to freeze the account.', 'Change your banking password and transaction PIN from a safe device.', 'Keep screenshots and transaction references for your report.', 'Report the incident to PNP Anti-Cybercrime Group.']],
  ['I clicked a phishing link', ['Disconnect the device from the internet if you entered credentials.', 'Change affected passwords from a separate, trusted device.', 'Clear browser data and run a complete security scan.', 'Monitor account activity and report unauthorized access.']],
  ['I paid an investment or job scam', ['Stop further transfers; do not pay a supposed release fee.', 'Report the payment to your bank, GCash, or Maya right away.', 'Preserve messages, receipts, account names, and phone numbers.', 'Report the incident to the relevant authorities.']],
];

function Brand({ onClick }) { return <button className="brand" onClick={onClick}><span className="brand-mark">◈</span><span className="brand-copy">SCAMSCAN<em>PH · EXPLAINABLE RISK CHECKS</em></span></button>; }
function RiskBadge({ level }) { return <span className={'risk-badge ' + String(level).toLowerCase()}>{level}</span>; }
function Empty({ children }) { return <p className="empty">{children}</p>; }
function Banner({ banner, onClose }) { return <div className={'notice ' + banner.kind}><span>{banner.text}</span>{onClose && <button onClick={onClose}>×</button>}</div>; }
function PageTitle({ tag, title, children, action }) { return <div className="page-head"><span className="eyebrow"><i />{tag}</span><h1>{title}</h1>{children && <p>{children}</p>}{action}</div>; }
function Metric({ label, value, accent = 'cyan' }) { return <article className={'metric ' + accent}><span>{label}</span><strong>{value ?? '—'}</strong></article>; }
function BarList({ rows = [], labelKey = '_id', valueKey = 'count', color = 'cyan' }) { const max = Math.max(...rows.map((row) => row[valueKey]), 1); return <div className="bar-list">{rows.length ? rows.map((row) => <div className="bar-row" key={row[labelKey]}><div><span>{row[labelKey] || 'Unknown'}</span><b>{row[valueKey]}</b></div><i className={color} style={{ width: ((row[valueKey] / max) * 100) + '%' }} /></div>) : <Empty>No data yet.</Empty>}</div>; }

function AuthCard({ title, subtitle, children, goHome }) { return <section className="auth-page"><div className="auth-layout"><div className="auth-card"><Brand onClick={goHome} /><span className="eyebrow"><i /> SECURE ACCOUNT ACCESS</span><h1>{title}</h1><p>{subtitle}</p>{children}</div><aside className="auth-aside"><span className="eyebrow"><i /> SCAMSCAN PH</span><h2>One careful check can change what happens next.</h2><p>Understand suspicious messages, review the signals behind a risk score, and keep your checks in one private workspace.</p><div><span>01</span> Verify your email<span>02</span> Check suspicious content<span>03</span> Decide with confidence</div></aside></div></section>; }
function PasswordRules({ value }) { return <div className="password-rules" aria-live="polite"><span className={value.length >= 8 && value.length <= 128 ? 'met' : ''}>8–128 characters</span><span className={/[A-Za-z]/.test(value) && /\d/.test(value) ? 'met' : ''}>Letter + number</span><span className={!/\s/.test(value) ? 'met' : ''}>No spaces</span></div>; }
function PasswordField({ label, name, autoComplete = 'current-password', required = true, minLength, onValueChange }) { const [visible, setVisible] = useState(false); return <label>{label}<span className="password-input"><input name={name} type={visible ? 'text' : 'password'} autoComplete={autoComplete} required={required} minLength={minLength} maxLength="128" onChange={(e) => onValueChange?.(e.target.value)} /><button type="button" aria-label={visible ? 'Hide password' : 'Show password'} title={visible ? 'Hide password' : 'Show password'} onClick={() => setVisible(!visible)}><svg viewBox="0 0 24 24" width="19" height="19" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="M2 12s3.6-6 10-6 10 6 10 6-3.6 6-10 6S2 12 2 12Z"/><circle cx="12" cy="12" r="2.5"/>{!visible && <path d="M3 21 21 3"/>}</svg></button></span></label>; }
function MemberOverview({ user, scanTotal, go }) { const guest = user.isGuest; return <section className="member-overview"><PageTitle tag={guest ? 'GUEST WORKSPACE' : 'MEMBER OVERVIEW'} title={guest ? 'Check first. Stay protected.' : 'Your ScamScan safety workspace.'}>{guest ? 'You can check messages, links and screenshots. Create an account for profile controls and private support.' : 'Check suspicious content, review previous results, and get help when a scam is suspected.'}</PageTitle><div className="metric-grid"><Metric label="Saved checks" value={scanTotal} /><Metric label="Access" value={guest ? 'Guest' : 'Member'} accent="purple" /><Metric label="Scanner" value="Ready" accent="amber" /></div><div className="overview-actions"><article className="panel"><span className="label">01 · DETECTOR</span><h2>Check a message, link or screenshot</h2><p>Get an explainable risk score and practical next step.</p><button className="primary" onClick={() => go('scanner')}>Open detector →</button></article><article className="panel"><span className="label">02 · REPORTS</span><h2>Review saved results</h2><p>Open a report to see the signals and recommendations behind its rating.</p><button className="secondary" onClick={() => go('history')}>View Scan History</button></article><article className="panel"><span className="label">03 · SUPPORT</span><h2>{guest ? 'Recovery information' : 'Ask for private help'}</h2><p>{guest ? 'Follow practical guidance for phishing, payment and OTP scams.' : 'Send a private request to a ScamScan administrator.'}</p><button className="secondary" onClick={() => go('help')}>Open Help Center</button></article></div>{guest && <article className="guest-upgrade"><b>Guest access has fewer account features.</b><span>Your scans stay with this guest session. Register for profile settings and private support.</span><button className="primary" onClick={() => go('register')}>Create an account</button></article>}</section>; }
function Landing({ go, guestLogin, busy }) { return <section className="landing clean-landing"><div className="hero-copy"><span className="eyebrow"><i />EXPLAINABLE SCAM RISK CHECKS</span><h1>Think first.<br /><b>Scan smarter.</b></h1><p>ScamScan helps you recognize suspicious messages, links, and screenshots before you take action. Create an account to save reports—or continue as a private guest.</p><div className="hero-actions"><button className="primary large-button" onClick={() => go('register')}>Create account</button><button className="secondary large-button" onClick={() => go('login')}>Sign in</button><button className="guest-button" disabled={busy} onClick={guestLogin}>{busy ? 'Opening guest access…' : 'Continue as Guest'}</button></div><p className="landing-note">Guest scans stay with this browser session. Scores are guidance, not proof of fraud.</p></div><aside className="landing-preview"><div className="preview-top"><span className="status-dot" /> EXAMPLE RISK CHECK</div><div className="preview-score"><b>82</b><span>HIGH RISK</span></div><div className="preview-copy"><span>Signals detected</span><p>OTP request · urgent prize · shortened link</p></div><div className="preview-line"><i /><i /><i /></div><small>Explainable results · private history · recovery guidance</small></aside><div className="landing-features"><article><span>01</span><h2>Scan</h2><p>Check message text, URLs, and image screenshots for common scam signals.</p></article><article><span>02</span><h2>Understand</h2><p>See clear risk scores, matched indicators, and recommended next actions.</p></article><article><span>03</span><h2>Respond</h2><p>Keep private reports and access recovery guidance when something goes wrong.</p></article></div></section>; }
function AnalysisResult({ analysis }) { return <div className="scan-result"><article className="score-panel"><div className="score-orb"><b>{analysis.score}</b><span>/ 100</span></div><div><span className="label">CATEGORY</span><h2>{analysis.level} risk</h2><p>{analysis.explanation}</p><RiskBadge level={analysis.level} /></div></article><article className="panel"><span className="label">WHY THIS WAS FLAGGED</span>{analysis.flags.length ? <ul className="flag-list">{analysis.flags.map((flag) => <li key={flag}>▸ <span>{flag}</span></li>)}</ul> : <Empty>No strong scam signals found.</Empty>}</article><article className="panel action-panel"><span className="label">WHAT TO DO NOW</span><p><b>Recommended:</b> {analysis.recommendation}</p></article></div>; }
function ReportDetail({ report, back }) { const signals = report.signals?.length ? report.signals : report.flags.map((label) => ({ label, points: 0 })); const max = Math.max(...signals.map((signal) => signal.points), 1); return <section><PageTitle tag="SAVED REPORT" title="Scan report details">Saved {new Date(report.createdAt).toLocaleString()}</PageTitle><button className="secondary page-action" onClick={back}>← Back to Scan History</button><div className="report-summary"><article className="score-panel"><div className="score-orb"><b>{report.score}</b><span>/ 100</span></div><div><span className="label">RISK CLASSIFICATION</span><h2>{report.level} risk</h2><p>{report.explanation}</p><RiskBadge level={report.level} /></div></article><article className="panel report-stats"><div><span>Language</span><b>{report.language}</b></div><div><span>Signals found</span><b>{report.flags.length}</b></div><div><span>Report date</span><b>{new Date(report.createdAt).toLocaleDateString()}</b></div></article><article className="panel"><span className="label">SUBMITTED CONTENT</span><p className="report-message">{report.message}</p></article><article className="panel"><span className="label">ANALYSIS BREAKDOWN</span><div className="signal-breakdown">{signals.map((signal) => <div key={signal.label}><div><span>{signal.label}</span><b>{signal.points ? '+' + signal.points : 'Detected'}</b></div><i style={{ width: ((signal.points / max) * 100) + '%' }} /></div>)}</div></article><article className="panel action-panel"><span className="label">RECOMMENDED ACTION</span><p>{report.recommendation}</p></article></div></section>; }
function ScannerPage({ scanMode, setScanMode, message, setMessage, imageFile, setImageFile, ocrProgress, analyze, analyzeImage, analysis, clearAnalysis, busy }) {
  const chooseMode = (mode) => { setScanMode(mode); setMessage(''); setImageFile(null); clearAnalysis(); };
  return <section className="detector-page"><PageTitle tag="SCAM DETECTOR" title="Check before you click.">Scan a suspicious message, link, or screenshot. Each completed check is saved to your private history.</PageTitle><div className="scanner"><div className="mode-selector" role="tablist" aria-label="Scan type">{[['text', 'Message', 'SMS, chat or email'], ['url', 'Link', 'Paste a website URL'], ['image', 'Screenshot', 'Read text from an image']].map(([mode, title, hint]) => <button key={mode} type="button" role="tab" aria-selected={scanMode === mode} className={scanMode === mode ? 'active' : ''} onClick={() => chooseMode(mode)}><b>{title}</b><small>{hint}</small></button>)}</div>{scanMode === 'image' ? <div className="image-scan-card"><label className="image-drop"><input type="file" accept="image/png,image/jpeg,image/webp" onChange={(e) => { setImageFile(e.target.files?.[0] || null); e.target.value = ''; }} /><span>▧</span><b>{imageFile ? imageFile.name : 'Choose a clear screenshot'}</b><small>PNG, JPG or WEBP, up to 5 MB. Visible text is extracted before checking.</small></label>{busy && <div className="ocr-progress"><i style={{ width: ocrProgress + '%' }} /><span>Reading image text… {ocrProgress}%</span></div>}<div className="scan-actions"><button className="primary" disabled={busy || !imageFile} onClick={analyzeImage}>{busy ? 'Checking screenshot…' : 'Read & check screenshot →'}</button></div></div> : <form onSubmit={analyze}><div className="input-card"><div><span className="pulse-dot" /> {scanMode === 'text' ? 'MESSAGE TO CHECK' : 'WEBSITE TO CHECK'}</div>{scanMode === 'text' ? <textarea value={message} onChange={(e) => setMessage(e.target.value)} placeholder="Paste the suspicious message here…" minLength="10" maxLength="5000" required /> : <input type="url" value={message} onChange={(e) => setMessage(e.target.value)} placeholder="https://example.com/login" maxLength="5000" required />}</div><p className="input-hint">Avoid pasting actual passwords, OTP codes, card numbers, or other private information.</p><div className="scan-actions"><button type="button" className="secondary" onClick={() => setMessage(scanMode === 'url' ? 'https://gcas-verify-claim.ph/login' : SAMPLE_SCAM)}>Use an example</button><button className="primary" disabled={busy || !message.trim()}>{busy ? 'Checking…' : 'Check risk →'}</button></div></form>}{analysis && <div className="result-wrap"><span className="eyebrow"><i /> CHECK COMPLETE · SAVED TO HISTORY</span><AnalysisResult analysis={analysis} /></div>}</div></section>;
}
function HistoryPage({ history, total, page, pages, level, setPage, setLevel, openReport, deleteScan }) { return <section><PageTitle tag="PRIVATE SCAN HISTORY" title="Your saved checks">Filter by risk level and open a report for its full explanation.</PageTitle><div className="history-tabs" role="tablist" aria-label="Risk level">{riskTabs.map((tab) => <button key={tab} role="tab" aria-selected={level === tab} className={level === tab ? 'active' : ''} onClick={() => { setLevel(tab); setPage(1); }}>{tab}</button>)}</div><p className="history-count">{total} {level === 'All' ? 'saved check' : level.toLowerCase() + ' risk check'}{total === 1 ? '' : 's'}</p><div className="history-list">{history.length ? history.map((item) => <article className="history-item" key={item._id}><RiskBadge level={item.level} /><button className="report-link" onClick={() => openReport(item)}><p>{item.message}</p><small>{new Date(item.createdAt).toLocaleString()} · {item.language} · {item.score}/100</small><b>View full report →</b></button><button className="delete-icon" onClick={() => deleteScan(item._id)}>Delete</button></article>) : <Empty>{level === 'All' ? 'Your first scan will appear here.' : 'No checks in this risk category.'}</Empty>}</div>{pages > 1 && <div className="pagination"><button className="secondary" disabled={page <= 1} onClick={() => setPage(page - 1)}>← Previous</button><span>Page {page} of {pages}</span><button className="secondary" disabled={page >= pages} onClick={() => setPage(page + 1)}>Next →</button></div>}</section>; }
function ProfilePage({ user, scanTotal, saveProfile, busy }) { return <section><PageTitle tag="ACCOUNT" title="Your profile">Manage your ScamScan account identity and access.</PageTitle><div className="two-col"><article className="profile-card"><div className="avatar">{user.name.slice(0, 1).toUpperCase()}</div><h2>{user.name}</h2><p>{user.email}</p><RiskBadge level={user.role === 'admin' ? 'Critical' : 'Safe'} /><small>Member since {new Date(user.createdAt).toLocaleDateString()}</small></article><form className="panel stack-form" onSubmit={saveProfile}><h2>Profile details</h2><label>Display name<input name="name" defaultValue={user.name} minLength="2" maxLength="80" required /></label><label>Email address<input value={user.email} disabled /></label><button className="primary" disabled={busy}>{busy ? 'Saving…' : 'Save profile'}</button></form></div><div className="metric-grid profile-metrics">{user.role !== 'admin' && <Metric label="Saved checks" value={scanTotal} />}<Metric label="Account role" value={user.role === 'admin' ? 'Admin' : 'Member'} accent="purple" /></div></section>; }
function SettingsPage({ user, savePreferences, changePassword, busy }) { return <section><PageTitle tag="ACCOUNT SETTINGS" title="Security and preferences">Control your ScamScan experience and keep your account secure.</PageTitle><div className="two-col"><form className="panel stack-form" onSubmit={savePreferences}><h2>Notifications</h2><label className="toggle-row"><span><b>Email notifications</b><small>Receive account and safety updates.</small></span><input name="emailNotifications" type="checkbox" defaultChecked={user.preferences?.emailNotifications} /></label><label className="toggle-row"><span><b>Scan safety tips</b><small>Show recommendations after every result.</small></span><input name="scanTips" type="checkbox" defaultChecked={user.preferences?.scanTips} /></label><button className="primary" disabled={busy}>{busy ? 'Saving…' : 'Save preferences'}</button></form><form className="panel stack-form" onSubmit={changePassword}><h2>Change password</h2><PasswordField label="Current password" name="currentPassword" /><PasswordField label="New password" name="newPassword" autoComplete="new-password" minLength="8" /><small>8–128 characters, a letter and a number, with no spaces.</small><PasswordField label="Confirm new password" name="confirmPassword" autoComplete="new-password" minLength="8" /><button className="secondary" disabled={busy}>{busy ? 'Updating…' : 'Change password'}</button></form></div></section>; }
function HelpPage({ user, sendHelp, busy, mySupport = [] }) {
  return <section><PageTitle tag="RECOVERY & SUPPORT" title="What happened?">Choose a situation for practical first steps. If money or account access is at risk, contact your provider right away.</PageTitle><div className="playbooks">{playbooks.map(([title, steps]) => <details className="playbook" key={title}><summary><span>⌁</span>{title}<b>⌄</b></summary><ol>{steps.map((step) => <li key={step}>{step}</li>)}</ol></details>)}</div>{!user.isGuest && <div className="two-col support-area"><form className="panel stack-form" onSubmit={sendHelp}><span className="label">PRIVATE HELP REQUEST</span><h2>Ask the ScamScan team</h2><p>Your request appears here immediately and in the administrator inbox. Email delivery requires SMTP configuration.</p><label>Subject<input name="subject" minLength="3" maxLength="140" required placeholder="Example: Suspicious payment request" /></label><label>What happened?<textarea name="message" minLength="10" maxLength="4000" required placeholder="Describe the issue without sharing passwords, OTPs, or card numbers." /></label><button className="primary" disabled={busy}>{busy ? 'Sending…' : 'Send private request'}</button></form><article className="panel support-history"><span className="label">YOUR REQUESTS</span>{mySupport.length ? mySupport.map((item) => <div key={item._id}><RiskBadge level={item.status === 'resolved' ? 'Safe' : item.status === 'in-progress' ? 'Warning' : 'High'} /><b>{item.subject}</b><p>{item.message}</p><small>{new Date(item.createdAt).toLocaleString()} · {item.status}</small>{item.replies?.map((reply) => <div className="support-reply" key={reply._id}><small>{reply.byName} replied · {new Date(reply.createdAt).toLocaleString()}</small><p>{reply.body}</p></div>)}</div>) : <Empty>No private requests yet.</Empty>}</article></div>}<article className="contact-panel"><span className="label">CONTACT YOUR PROVIDER OR AUTHORITIES</span><div><p><b>Bank or payment app</b><br />Use its official app or known support number to freeze affected access.</p><p><b>Report the scam</b><br />Keep messages and transaction references for an official report.</p><p><b>Protect your accounts</b><br />Change passwords from a trusted device and monitor activity.</p></div></article></section>;
}
function AboutPage() { return <section className="about-page"><PageTitle tag="ABOUT SCAMSCAN" title="A safer digital Philippines starts with a pause.">ScamScan is an educational capstone application for understanding scam signals and practicing safe response decisions.</PageTitle><div className="two-col"><article className="panel"><h2>Our mission</h2><p>Make scam awareness simple, explainable, and accessible for English, Tagalog, and Taglish messages.</p></article><article className="panel"><h2>How it works</h2><p>ScamScan checks visible scam patterns such as urgency, financial requests, OTP requests, suspicious links, prizes, and impersonation language.</p></article><article className="panel"><h2>Your privacy</h2><p>Your saved analyses belong to your user account. Avoid submitting OTPs, passwords, card numbers, account numbers, or other sensitive data.</p></article><article className="panel"><h2>Important limitation</h2><p>A result is a risk indicator, not proof. Verify through official apps, websites, or known support numbers before taking action.</p></article></div></section>; }

function CyberDashboard({ dashboard, refresh, updateAlert, busy }) { return <section><PageTitle tag="ADMIN CONSOLE" title="CyberShield overview">Only administrators can access and respond to simulated security events.</PageTitle><button className="secondary page-action" onClick={refresh}>Refresh dashboard</button>{dashboard ? <><div className="metric-grid"><Metric label="Events today" value={dashboard.metrics.eventsToday} /><Metric label="Open alerts" value={dashboard.metrics.openAlerts} accent="red" /><Metric label="Active users" value={dashboard.metrics.activeUsers} accent="purple" /><Metric label="Known devices" value={dashboard.metrics.activeDevices} accent="amber" /></div><div className="chart-grid"><article className="panel"><h2>Threat severity</h2><BarList rows={dashboard.bySeverity} color="red" /></article><article className="panel"><h2>Attack types</h2><BarList rows={dashboard.byType} color="purple" /></article><article className="panel"><h2>Highest-risk users</h2><BarList rows={dashboard.highRiskUsers} labelKey="actor" valueKey="maxScore" color="amber" /></article><article className="panel"><h2>File activity</h2><BarList rows={dashboard.fileActivity} labelKey="_id" valueKey="files" /></article><article className="panel wide"><h2>Live alert feed</h2><div className="alert-feed">{dashboard.alerts.length ? dashboard.alerts.map((alert) => <article className="alert-item" key={alert._id}><RiskBadge level={alert.severity} /><div><b>{alert.actor}</b><p>{alert.summary}</p><small>{new Date(alert.createdAt).toLocaleString()} · {alert.score}/100 · {alert.status}</small><div className="alert-actions">{alert.status === 'open' && <button disabled={busy} onClick={() => updateAlert(alert._id, 'acknowledged')}>Acknowledge</button>}{alert.status !== 'resolved' && <button disabled={busy} onClick={() => updateAlert(alert._id, 'resolved')}>Resolve</button>}</div></div></article>) : <Empty>No high-risk activity saved.</Empty>}</div></article></div></> : <Empty>Loading dashboard…</Empty>}</section>; }
function EventForm({ event, setEvent, busy, submit }) { const inputs = [['isNewDevice', 'New device'], ['isUnknownIp', 'Unknown IP'], ['isUnusualTime', 'Unusual login time'], ['restrictedFolder', 'Restricted folder accessed'], ['portScan', 'Port-scan signs'], ['unusualTraffic', 'Unusual traffic volume']]; return <form className="event-form panel" onSubmit={submit}><div className="field-grid"><label>Activity type<select value={event.type} onChange={(e) => setEvent({ ...event, type: e.target.value })}><option value="login">Login activity</option><option value="file">File activity</option><option value="network">Network activity</option><option value="behavior">User behavior</option></select></label><label>User / actor<input value={event.actor} onChange={(e) => setEvent({ ...event, actor: e.target.value })} required /></label><label>Observed at<input type="datetime-local" value={event.occurredAt} onChange={(e) => setEvent({ ...event, occurredAt: e.target.value })} /></label><label>IP address<input value={event.ip} onChange={(e) => setEvent({ ...event, ip: e.target.value })} /></label><label>Device<input value={event.device} onChange={(e) => setEvent({ ...event, device: e.target.value })} /></label><label>Location<input value={event.location} onChange={(e) => setEvent({ ...event, location: e.target.value })} /></label><label>Failed attempts<input type="number" min="0" value={event.failedAttempts} onChange={(e) => setEvent({ ...event, failedAttempts: e.target.value })} /></label><label>Files affected<input type="number" min="0" value={event.fileCount} onChange={(e) => setEvent({ ...event, fileCount: e.target.value })} /></label></div><fieldset><legend>Risk indicators</legend>{inputs.map(([key, label]) => <label className="checkbox" key={key}><input type="checkbox" checked={event[key]} onChange={(e) => setEvent({ ...event, [key]: e.target.checked })} />{label}</label>)}</fieldset><button className="primary" disabled={busy}>{busy ? 'Creating…' : 'Score and save event'}</button></form>; }
function AdminOverview({ data, go }) { return <section><PageTitle tag="ADMIN CONTROL CENTER" title="ScamScan administration">A protected workspace for account oversight, reports, help requests, and auditable platform activity.</PageTitle>{data ? <><div className="metric-grid"><Metric label="Member accounts" value={data.accounts} /><Metric label="Guest sessions" value={data.guests} accent="purple" /><Metric label="Verified members" value={data.verified} accent="amber" /><Metric label="All reports" value={data.reports} accent="red" /><Metric label="Open help requests" value={data.openSupport} accent="red" /></div><div className="overview-actions admin-quick"><article className="panel"><span className="label">REPORT ACCESS</span><h2>Every scan report</h2><p>Review member and guest analysis results with their full indicators.</p><button className="primary" onClick={() => go('adminReports')}>Open reports</button></article><article className="panel"><span className="label">ACCOUNT CONTROL</span><h2>Account management</h2><p>Open a complete account record, edit access, or remove data.</p><button className="secondary" onClick={() => go('adminUsers')}>Manage accounts</button></article><article className="panel"><span className="label">AUDITABILITY</span><h2>Audit log</h2><p>Review recorded login, scan, profile, and administrator actions.</p><button className="secondary" onClick={() => go('adminAudit')}>View audit log</button></article></div><article className="panel audit-preview"><span className="label">LATEST ACTIVITY</span>{data.latestAudit?.length ? data.latestAudit.map((log) => <p key={log._id}><b>{log.actorName}</b> · {log.action.replaceAll('.', ' ')} <small>{new Date(log.createdAt).toLocaleString()}</small></p>) : <Empty>No activity logged yet.</Empty>}</article></> : <Empty>Loading administrator overview…</Empty>}</section>; }
function AdminAnalysis({ analytics, refresh }) { return <section><PageTitle tag="SYSTEM ANALYSIS" title="What the checks are finding">Live aggregate data from saved scans. These are rule-based risk estimates, not confirmed fraud cases.</PageTitle><button className="secondary page-action" onClick={refresh}>Refresh analysis</button>{analytics ? <><div className="metric-grid"><Metric label="Total checks" value={analytics.total} /><Metric label="High or Scam" value={String(analytics.highRiskRate) + '%'} accent="red" /><Metric label="Average risk score" value={analytics.averageScore + '/100'} accent="amber" /><Metric label="Admin reviewed" value={analytics.reviewed} accent="purple" /></div><div className="chart-grid"><article className="panel"><h2>Risk levels</h2><BarList rows={analytics.byLevel} color="red" /></article><article className="panel"><h2>Checks in the last 7 days</h2><BarList rows={analytics.trend} color="cyan" /></article><article className="panel"><h2>Most common detected signals</h2><BarList rows={analytics.commonFlags} color="amber" /></article><article className="panel"><h2>Language patterns</h2><BarList rows={analytics.byLanguage} color="purple" /></article><article className="panel wide"><h2>Member and guest checks</h2><BarList rows={analytics.byAccountType} color="cyan" /><p className="analysis-note">Scores depend on visible patterns. A low score does not guarantee that a message or website is safe.</p></article></div></> : <Empty>Loading system analysis…</Empty>}</section>; }
function AdminReports({ reports, total, page, pages, level, setPage, setLevel, openReport }) { return <section><PageTitle tag="REPORT REVIEW" title="All scan reports">Inspect member and guest checks, then edit a report when a human review finds a better assessment.</PageTitle><div className="history-tabs" role="tablist" aria-label="Report risk level">{riskTabs.map((tab) => <button key={tab} role="tab" aria-selected={level === tab} className={level === tab ? 'active' : ''} onClick={() => { setLevel(tab); setPage(1); }}>{tab}</button>)}</div><p className="history-count">{total} reports in this view</p><div className="history-list">{reports.length ? reports.map((report) => <article className="history-item" key={report._id}><RiskBadge level={report.level} /><button className="report-link" onClick={() => openReport(report)}><p>{report.message}</p><small>{report.user?.isGuest ? 'Guest' : report.user?.name || 'Former member'} · {new Date(report.createdAt).toLocaleString()} · {report.score}/100</small><b>Open and review →</b></button></article>) : <Empty>No reports in this category.</Empty>}</div>{pages > 1 && <div className="pagination"><button className="secondary" disabled={page <= 1} onClick={() => setPage(page - 1)}>← Previous</button><span>Page {page} of {pages}</span><button className="secondary" disabled={page >= pages} onClick={() => setPage(page + 1)}>Next →</button></div>}</section>; }
function AdminReportEditor({ report, save, busy }) { return <form className="panel stack-form admin-report-editor" onSubmit={save} key={report._id}><span className="label">HUMAN REVIEW</span><h2>Edit this assessment</h2><p>Changes update the saved report. The original detected signals remain visible, and your review is recorded in the audit log.</p><div className="field-grid"><label>Risk score<input type="number" name="score" min="0" max="100" defaultValue={report.score} required /></label><label>Risk level<select name="level" defaultValue={report.level}><option>Safe</option><option>Warning</option><option>High</option><option>Scam</option></select></label></div><label>Explanation<textarea name="explanation" minLength="10" maxLength="1000" defaultValue={report.explanation} required /></label><label>Recommendation<textarea name="recommendation" minLength="10" maxLength="1000" defaultValue={report.recommendation} required /></label><label>Review note<textarea name="note" maxLength="500" defaultValue={report.adminReview?.note || ''} placeholder="Why did you change this assessment?" /></label><button className="primary" disabled={busy}>{busy ? 'Saving review…' : 'Save reviewed report'}</button></form>; }
function AuditLogPage({ logs }) { return <section><PageTitle tag="ADMIN AUDIT LOG" title="Recorded platform activity">Security-relevant actions are captured automatically so administrators can trace account and report activity.</PageTitle><div className="panel audit-log">{logs.length ? logs.map((log) => <article key={log._id}><div><b>{log.action.replaceAll('.', ' ')}</b><p>{log.actorName} · {log.actorEmail} · {log.actorRole}</p>{log.details && <small>{log.details}</small>}</div><time>{new Date(log.createdAt).toLocaleString()}</time></article>) : <Empty>No events have been recorded yet.</Empty>}</div></section>; }
function AdminSupport({ items, busy, updateStatus, replyToHelp }) { return <section><PageTitle tag="HELP INBOX" title="Private support requests">Read messages, reply to members, and keep the status up to date. Replies also appear in the member's Help Center.</PageTitle><div className="admin-support-list">{items.length ? items.map((item) => <article className="panel support-ticket" key={item._id}><div className="ticket-head"><div><span className="label">{new Date(item.createdAt).toLocaleString()}</span><h2>{item.subject}</h2><p>{item.senderName} · {item.senderEmail}</p></div><select aria-label={'Status for ' + item.subject} value={item.status} disabled={busy} onChange={(e) => updateStatus(item._id, e.target.value)}><option value="open">Open</option><option value="in-progress">In progress</option><option value="resolved">Resolved</option></select></div><p className="ticket-message">{item.message}</p>{item.replies?.map((reply) => <div className="support-reply" key={reply._id}><small>{reply.byName} · {new Date(reply.createdAt).toLocaleString()}</small><p>{reply.body}</p></div>)}<form className="stack-form" onSubmit={(e) => { e.preventDefault(); const form = e.currentTarget; replyToHelp(item._id, new FormData(form).get('body'), form); }}><label>Reply to member<textarea name="body" minLength="10" maxLength="4000" required placeholder="Write a clear, helpful reply…" /></label><button className="primary" disabled={busy}>{busy ? 'Sending…' : 'Send reply'}</button></form></article>) : <Empty>Your help inbox is clear.</Empty>}</div></section>; }
function AccountDetails({ details, back, openReport }) { if (!details) return <Empty>Loading account details…</Empty>; const { user, analyses, events, support, audit } = details; return <section><PageTitle tag="MEMBER RECORD" title={user.name}>{user.email} · {user.role} · {user.isActive ? 'Active' : 'Suspended'} · {user.emailVerified ? 'Verified' : 'Unverified'}</PageTitle><button className="secondary page-action" onClick={back}>← Back to accounts</button><div className="metric-grid"><Metric label="Recent reports" value={analyses.length} /><Metric label="Security events" value={events.length} accent="amber" /><Metric label="Support requests" value={support.length} accent="purple" /><Metric label="Audit entries" value={audit.length} accent="red" /></div><div className="chart-grid"><article className="panel"><h2>Scan reports</h2>{analyses.length ? analyses.map((x) => <button className="record-link" key={x._id} onClick={() => openReport(x)}><RiskBadge level={x.level} /><span>{x.message.slice(0, 80)}…<small>{new Date(x.createdAt).toLocaleString()} · {x.score}/100</small></span></button>) : <Empty>No saved scans.</Empty>}</article><article className="panel"><h2>Audit activity</h2>{audit.length ? audit.map((x) => <p key={x._id}><b>{x.action.replaceAll('.', ' ')}</b><br /><small>{new Date(x.createdAt).toLocaleString()}</small></p>) : <Empty>No activity yet.</Empty>}</article><article className="panel"><h2>Help requests</h2>{support.length ? support.map((x) => <p key={x._id}><b>{x.subject}</b> · {x.status}<br /><span>{x.message}</span></p>) : <Empty>No help requests.</Empty>}</article><article className="panel"><h2>Simulated security events</h2>{events.length ? events.map((x) => <p key={x._id}><b>{x.type}</b> · {x.severity} · {x.status}<br /><small>{new Date(x.createdAt).toLocaleString()}</small></p>) : <Empty>No simulated events.</Empty>}</article></div></section>; }
function AccountRow({ member, busy, onChange, onDelete, onDetails }) {
  const [editing, setEditing] = useState(false);
  const save = async (event) => {
    event.preventDefault();
    const values = Object.fromEntries(new FormData(event.currentTarget));
    const saved = await onChange(member._id, { name: values.name, email: values.email, role: values.role });
    if (saved) setEditing(false);
  };
  return <article className="panel account-row"><div className="account-row-top"><div><b>{member.name}</b><p>{member.email}</p><small>{member.emailVerified ? 'Verified' : 'Awaiting verification'} · {member.isActive ? 'Active' : 'Suspended'} · Joined {new Date(member.createdAt).toLocaleDateString()}</small></div><span className="account-role">{member.role}</span></div><div className="account-actions"><button className="secondary" onClick={() => onDetails(member._id)}>Full record</button><button className="secondary" onClick={() => setEditing(!editing)}>{editing ? 'Close editor' : 'Edit details'}</button><button className="secondary" disabled={busy} onClick={() => onChange(member._id, { isActive: !member.isActive })}>{member.isActive ? 'Suspend' : 'Activate'}</button><button className="danger-button" disabled={busy} onClick={() => onDelete(member)}>Delete</button></div>{editing && <form className="account-edit stack-form" onSubmit={save}><div className="field-grid"><label>Display name<input name="name" defaultValue={member.name} minLength="2" maxLength="80" required /></label><label>Email address<input name="email" type="email" defaultValue={member.email} maxLength="254" required /></label><label>Access role<select name="role" defaultValue={member.role}><option value="user">Member</option><option value="admin">Administrator</option></select></label></div><button className="primary" disabled={busy}>Save account changes</button></form>}</article>;
}
function UserManagement({ users, busy, onChange, onDelete, onDetails }) { return <section><PageTitle tag="ACCOUNT MANAGEMENT" title="Member accounts">Review access, update account information, or open a full record. Guest sessions are excluded from this directory.</PageTitle><div className="account-list">{users.length ? users.map((member) => <AccountRow key={member._id} member={member} busy={busy} onChange={onChange} onDelete={onDelete} onDetails={onDetails} />) : <Empty>No member accounts found.</Empty>}</div></section>; }

export default function App() {
  const [page, setPage] = useState('home');
  const [user, setUser] = useState(null);
  const [checkingSession, setCheckingSession] = useState(true);
  const [busy, setBusy] = useState(false);
  const [scanMode, setScanMode] = useState('text');
  const [message, setMessage] = useState('');
  const [imageFile, setImageFile] = useState(null);
  const [ocrProgress, setOcrProgress] = useState(0);
  const [analysis, setAnalysis] = useState(null);
  const [history, setHistory] = useState([]);
  const [scanTotal, setScanTotal] = useState(0);
  const [historyTotal, setHistoryTotal] = useState(0);
  const [historyPage, setHistoryPage] = useState(1);
  const [historyPages, setHistoryPages] = useState(1);
  const [historyLevel, setHistoryLevel] = useState('All');
  const [selectedReport, setSelectedReport] = useState(null);
  const [dashboard, setDashboard] = useState(null);
  const [analytics, setAnalytics] = useState(null);
  const [users, setUsers] = useState([]);
  const [banner, setBanner] = useState(null);
  const [forgotResult, setForgotResult] = useState(null);
  const [pendingEmail, setPendingEmail] = useState('');
  const [pendingDevOtp, setPendingDevOtp] = useState('');
  const [adminOverview, setAdminOverview] = useState(null);
  const [adminReports, setAdminReports] = useState([]);
  const [adminReportTotal, setAdminReportTotal] = useState(0);
  const [adminReportPage, setAdminReportPage] = useState(1);
  const [adminReportPages, setAdminReportPages] = useState(1);
  const [adminReportLevel, setAdminReportLevel] = useState('All');
  const [auditLogs, setAuditLogs] = useState([]);
  const [supportInbox, setSupportInbox] = useState([]);
  const [mySupport, setMySupport] = useState([]);
  const [accountDetails, setAccountDetails] = useState(null);
  const [loginCooldown, setLoginCooldown] = useState(0);
  const [registrationPassword, setRegistrationPassword] = useState('');
  const accountRef = useRef(null);
  const historyRequestRef = useRef(0);
  const adminReportRequestRef = useRef(0);
  const mySupportRequestRef = useRef(0);
  const supportInboxRequestRef = useRef(0);
  const [event, setEvent] = useState({ type: 'login', actor: 'j.delacruz', ip: '185.220.101.8', device: 'Unknown Windows device', location: 'Unknown', occurredAt: new Date().toISOString().slice(0, 16), failedAttempts: 12, isNewDevice: true, isUnknownIp: true, isUnusualTime: true, fileCount: 0, restrictedFolder: false, portScan: false, unusualTraffic: false });
  const isAdmin = user?.role === 'admin';
  const go = (next) => { setBanner(null); setPage(next); };
  const error = (text) => setBanner({ kind: 'error', text });
  const success = (text) => setBanner({ kind: 'success', text });
  useEffect(() => { api.getMe().then(({ user: account }) => { setUser(account); setPage(account.role === 'admin' ? 'adminOverview' : 'home'); }).catch(() => setUser(null)).finally(() => setCheckingSession(false)); }, []);
  useEffect(() => { if (accountRef.current === (user?.id || null)) return; accountRef.current = user?.id || null; setMessage(''); setImageFile(null); setAnalysis(null); setOcrProgress(0); setScanMode('text'); setHistory([]); setHistoryPage(1); setHistoryLevel('All'); setScanTotal(0); setMySupport([]); setSelectedReport(null); setAccountDetails(null); setAdminReports([]); setAdminOverview(null); }, [user?.id]);
  useEffect(() => { if (!loginCooldown) return; const timer = setInterval(() => setLoginCooldown((seconds) => Math.max(0, seconds - 1)), 1000); return () => clearInterval(timer); }, [loginCooldown > 0]);
  useEffect(() => { if (!user) return; if (page === 'history') loadHistory(); if (['home', 'profile'].includes(page) && !isAdmin) loadScanTotal(); if (page === 'help' && !user.isGuest) loadMySupport(); if (page === 'adminOverview' && isAdmin) loadAdminOverview(); if (page === 'adminAnalytics' && isAdmin) loadAnalytics(); if (page === 'adminCyber' && isAdmin) loadDashboard(); if (page === 'adminUsers' && isAdmin) loadUsers(); if (page === 'adminReports' && isAdmin) loadAdminReports(); if (page === 'adminAudit' && isAdmin) loadAuditLogs(); if (page === 'adminSupport' && isAdmin) loadSupportInbox(); }, [page, user?.id, isAdmin, historyPage, historyLevel, adminReportPage, adminReportLevel]);
  async function run(task, minimumDelay = 450) { const account = accountRef.current; setBusy(true); setBanner(null); const started = Date.now(); try { const result = await task(); const remaining = minimumDelay - (Date.now() - started); if (remaining > 0) await new Promise((resolve) => setTimeout(resolve, remaining)); return result; } catch (e) { if (account === accountRef.current) { if (e.retryAfter) setLoginCooldown(e.retryAfter); error(e.message); } return null; } finally { setBusy(false); } }
  async function loadHistory() { const account = accountRef.current; const requestId = ++historyRequestRef.current; const result = await run(() => api.getScamHistory({ page: historyPage, level: historyLevel }), 0); if (result && account === accountRef.current && requestId === historyRequestRef.current) { setHistory(result.analyses); setHistoryTotal(result.total); setHistoryPages(result.pages); setScanTotal((current) => historyLevel === 'All' ? result.total : current); } }
  async function loadScanTotal() { const account = accountRef.current; const result = await run(() => api.getScamHistory({ page: 1 }), 0); if (result && account === accountRef.current) setScanTotal(result.total); }
  async function loadAnalytics() { const account = accountRef.current; const result = await run(api.getScamAnalytics); if (result && account === accountRef.current) setAnalytics(result); }
  async function loadDashboard() { const account = accountRef.current; const result = await run(api.getThreatDashboard); if (result && account === accountRef.current) setDashboard(result); }
  async function loadUsers() { const account = accountRef.current; const result = await run(api.getUsers); if (result && account === accountRef.current) setUsers(result.users); }
  async function loadAdminOverview() { const account = accountRef.current; const result = await run(api.getAdminOverview); if (result && account === accountRef.current) setAdminOverview(result); }
  async function loadAdminReports() { const account = accountRef.current; const requestId = ++adminReportRequestRef.current; const result = await run(() => api.getAdminReports({ page: adminReportPage, level: adminReportLevel }), 0); if (result && account === accountRef.current && requestId === adminReportRequestRef.current) { setAdminReports(result.reports); setAdminReportTotal(result.total); setAdminReportPages(result.pages); } }
  async function loadAuditLogs() { const account = accountRef.current; const result = await run(api.getAuditLogs); if (result && account === accountRef.current) setAuditLogs(result.logs); }
  async function loadSupportInbox() { const account = accountRef.current; const requestId = ++supportInboxRequestRef.current; const result = await run(api.getAdminSupport); if (result && account === accountRef.current && requestId === supportInboxRequestRef.current) setSupportInbox(result.support); }
  async function loadMySupport() { const account = accountRef.current; const requestId = ++mySupportRequestRef.current; const result = await run(api.getMySupport); if (result && account === accountRef.current && requestId === mySupportRequestRef.current) setMySupport(result.support); }
  async function register(e) { e.preventDefault(); const data = Object.fromEntries(new FormData(e.currentTarget)); if (data.password !== data.confirmPassword) return error('The password confirmation does not match.'); const issue = passwordIssue(data.password); if (issue) return error(issue); const result = await run(() => api.register(data)); if (result) { setPendingEmail(result.email); setPendingDevOtp(result.devOtp || ''); go('verify'); success(result.message); } }
  async function verifyEmail(e) { e.preventDefault(); const data = new FormData(e.currentTarget); const email = data.get('email') || pendingEmail; const result = await run(() => api.verifyEmail(email, data.get('code'))); if (result) { setPendingEmail(email); setUser(result.user); setPendingDevOtp(''); go('home'); success('Email verified. Your ScamScan account is ready.'); } }
  async function resendVerification() { if (!pendingEmail) return error('Enter your email address first.'); const result = await run(() => api.resendVerification(pendingEmail)); if (result) { setPendingDevOtp(result.devOtp || ''); success(result.message); } }
  async function login(e) { e.preventDefault(); if (loginCooldown) return; const data = Object.fromEntries(new FormData(e.currentTarget)); const result = await run(() => api.login(data)); if (result) { setUser(result.user); setLoginCooldown(0); go(result.user.role === 'admin' ? 'adminOverview' : 'home'); } }
  async function guestLogin() { const result = await run(api.loginAsGuest, 650); if (result) { setUser(result.user); go('home'); success('Guest access is ready.'); } }
  async function logout() { const result = await run(api.logout); if (result !== null) { setUser(null); go('home'); } }
  async function forgot(e) { e.preventDefault(); const email = new FormData(e.currentTarget).get('email'); const result = await run(() => api.forgotPassword(email)); if (result) { setPendingEmail(email); setPendingDevOtp(result.devOtp || ''); setForgotResult(result); go('reset'); } }
  async function reset(e) { e.preventDefault(); const data = Object.fromEntries(new FormData(e.currentTarget)); if (data.password !== data.confirmPassword) return error('The password confirmation does not match.'); const issue = passwordIssue(data.password); if (issue) return error(issue); const result = await run(() => api.resetPassword(data.email, data.code, data.password)); if (result) { setPendingDevOtp(''); go('login'); success(result.message); } }
  async function analyze(e) { e.preventDefault(); const account = accountRef.current; const submitted = message.trim(); if (submitted.length < 10) return error('Enter at least 10 characters to check.'); const result = await run(() => api.analyzeMessage(submitted)); if (result && account === accountRef.current) { setAnalysis(result); setMessage(''); setScanTotal((count) => count + 1); success('Check complete. The input is clear for your next scan.'); } }
  async function analyzeImage() { const account = accountRef.current; if (!imageFile) return error('Choose an image before starting image detection.'); if (!['image/png', 'image/jpeg', 'image/webp'].includes(imageFile.type) || imageFile.size > 5 * 1024 * 1024) return error('Choose a PNG, JPG, or WEBP screenshot under 5 MB.'); const result = await run(async () => { const worker = await createWorker('eng', 1, { logger: (event) => { if (account === accountRef.current && event.status === 'recognizing text') setOcrProgress(Math.round((event.progress || 0) * 100)); } }); try { const response = await worker.recognize(imageFile); const extractedText = response.data.text.trim(); if (extractedText.length < 10) throw new Error('Not enough readable text was found. Try a clearer screenshot or paste its text.'); return api.analyzeMessage(extractedText); } finally { await worker.terminate(); } }, 650); if (result && account === accountRef.current) { setAnalysis(result); setMessage(''); setImageFile(null); setOcrProgress(0); setScanTotal((count) => count + 1); success('Screenshot checked and saved. The image input is clear for your next scan.'); } }
  async function deleteScan(id) { if (!window.confirm('Delete this saved scan?')) return; const result = await run(() => api.deleteScan(id)); if (result !== null) loadHistory(); }
  async function saveProfile(e) { e.preventDefault(); const result = await run(() => api.updateProfile(new FormData(e.currentTarget).get('name'))); if (result) { setUser(result.user); success('Profile saved.'); } }
  async function savePreferences(e) { e.preventDefault(); const data = new FormData(e.currentTarget); const result = await run(() => api.updatePreferences({ emailNotifications: data.get('emailNotifications') === 'on', scanTips: data.get('scanTips') === 'on' })); if (result) { setUser(result.user); success('Preferences saved.'); } }
  async function changePassword(e) { e.preventDefault(); const data = Object.fromEntries(new FormData(e.currentTarget)); if (data.newPassword !== data.confirmPassword) return error('The password confirmation does not match.'); const issue = passwordIssue(data.newPassword); if (issue) return error(issue); const result = await run(() => api.changePassword(data.currentPassword, data.newPassword)); if (result) { setUser(null); go('login'); success(result.message); } }
  async function createEvent(e) { e.preventDefault(); const result = await run(() => api.createEvent({ ...event, failedAttempts: Number(event.failedAttempts), fileCount: Number(event.fileCount) })); if (result) { go('adminCyber'); loadDashboard(); } }
  async function seedDemo() { const result = await run(api.seedDemo); if (result) { go('adminCyber'); loadDashboard(); } }
  async function updateAlert(id, status) { const result = await run(() => api.updateAlertStatus(id, status)); if (result) loadDashboard(); }
  async function manageUser(id, data) { const result = await run(() => api.updateUser(id, data)); if (result) { success('User access updated.'); loadUsers(); } return Boolean(result); }
  async function removeUser(member) { if (!window.confirm('Permanently delete ' + member.email + ' and their saved data?')) return; const result = await run(() => api.deleteUser(member._id)); if (result !== null) { success('User and associated saved data deleted.'); loadUsers(); } }
  async function openAccountDetails(id) { const result = await run(() => api.getUserDetails(id)); if (result) { setAccountDetails(result); go('adminAccountDetails'); } }
  async function updateSupportStatus(id, status) { const result = await run(() => api.updateSupportStatus(id, status)); if (result) { success('Support status updated.'); loadSupportInbox(); } }
  async function sendHelp(e) { e.preventDefault(); const account = accountRef.current; const form = e.currentTarget; const data = new FormData(form); const result = await run(() => api.sendSupport(data.get('subject'), data.get('message'))); if (result && account === accountRef.current) { ++mySupportRequestRef.current; form.reset(); setMySupport((items) => [result.support, ...items]); success('Your request was saved and is visible below.'); } }
  async function replyToHelp(id, body, form) { const account = accountRef.current; const result = await run(() => api.replyToSupport(id, body)); if (result && account === accountRef.current) { ++supportInboxRequestRef.current; form.reset(); setSupportInbox((items) => items.map((item) => item._id === id ? result.support : item)); success(result.emailed ? 'Reply saved and emailed to the member.' : 'Reply saved. The member can read it in Help Center.'); } }
  async function saveAdminReport(e) { e.preventDefault(); const data = Object.fromEntries(new FormData(e.currentTarget)); const result = await run(() => api.updateAdminReport(selectedReport._id, data)); if (result) { setSelectedReport(result.report); setAdminReports((items) => items.map((item) => item._id === result.report._id ? result.report : item)); success('Reviewed report saved and logged.'); } }

  if (checkingSession) return <div className="loading-screen">Loading ScamScan…</div>;
  const authProps = { goHome: () => go('home') };
  if (page === 'login') return <AuthCard {...authProps} title="Welcome back" subtitle="Sign in to continue to your ScamScan workspace."><form className="stack-form" onSubmit={login}><label>Email address<input name="email" type="email" autoComplete="email" maxLength="254" required placeholder="you@example.com" /></label><PasswordField label="Password" name="password" /><button className="primary auth-action" disabled={busy || loginCooldown > 0}>{loginCooldown ? `Try again in ${Math.ceil(loginCooldown / 60)} min` : busy ? 'Signing in…' : 'Sign in securely'}</button></form>{loginCooldown > 0 && <p className="cooldown-note">Too many incorrect passwords. Wait {Math.ceil(loginCooldown / 60)} minute{loginCooldown > 60 ? 's' : ''}, then try again.</p>}<div className="auth-divider"><span>OR</span></div><button className="guest-button full" disabled={busy} onClick={guestLogin}>Continue as Guest</button><div className="auth-links"><button className="text-button center" onClick={() => go('forgot')}>Forgot password?</button><button className="text-button center" onClick={() => go('verify')}>Verify an email</button></div><p className="auth-switch">New here? <button className="inline-button" onClick={() => go('register')}>Create an account</button></p>{banner && <Banner banner={banner} />}</AuthCard>;
  if (page === 'register') return <AuthCard {...authProps} title="Create your account" subtitle="We send a code first. Your account is created only after you verify your email."><form className="stack-form" onSubmit={register}><label>Full name<input name="name" minLength="2" maxLength="80" autoComplete="name" required placeholder="Your full name" /></label><label>Email address<input name="email" type="email" maxLength="254" autoComplete="email" required placeholder="you@example.com" /></label><PasswordField label="Password" name="password" autoComplete="new-password" minLength="8" onValueChange={setRegistrationPassword} /><PasswordRules value={registrationPassword} /><PasswordField label="Confirm password" name="confirmPassword" autoComplete="new-password" minLength="8" /><button className="primary auth-action" disabled={busy}>{busy ? 'Sending verification code…' : 'Send verification code'}</button></form><p className="auth-switch">Already registered? <button className="inline-button" onClick={() => go('login')}>Sign in</button></p>{banner && <Banner banner={banner} />}</AuthCard>;
  if (page === 'verify') return <AuthCard {...authProps} title="Verify your email" subtitle={pendingEmail ? 'Enter the six-digit code sent to ' + pendingEmail + '. It expires in 10 minutes.' : 'Enter your email address and the six-digit verification code.'}><form className="stack-form" onSubmit={verifyEmail}><label>Email<input name="email" type="email" autoComplete="email" value={pendingEmail} onChange={(e) => setPendingEmail(e.target.value)} required /></label><label>Verification code<input name="code" autoComplete="one-time-code" inputMode="numeric" pattern="[0-9]{6}" maxLength="6" placeholder="Enter the six-digit code" required /></label><button className="primary" disabled={busy}>{busy ? 'Verifying…' : 'Verify & sign in'}</button></form>{pendingDevOtp && <div className="info-card"><b>Development-only code</b><p>{pendingDevOtp}</p><small>Configure SMTP in server/.env before deploying. This code is never returned in production.</small></div>}<button className="text-button center" disabled={busy} onClick={resendVerification}>Send a new code</button>{banner && <Banner banner={banner} />}</AuthCard>;
  if (page === 'forgot') return <AuthCard {...authProps} title="Reset password" subtitle="We will send a six-digit password-reset code to your verified account email."><form className="stack-form" onSubmit={forgot}><label>Email<input name="email" type="email" required /></label><button className="primary" disabled={busy}>{busy ? 'Sending…' : 'Send reset code'}</button></form><button className="text-button center" onClick={() => go('login')}>Back to sign in</button>{banner && <Banner banner={banner} />}</AuthCard>;
  if (page === 'reset') return <AuthCard {...authProps} title="Choose a new password" subtitle={'Enter the six-digit code sent to ' + pendingEmail + '.'}><form className="stack-form" onSubmit={reset}><label>Email<input name="email" type="email" autoComplete="email" value={pendingEmail} required /></label><label>Reset code<input name="code" autoComplete="one-time-code" inputMode="numeric" pattern="[0-9]{6}" maxLength="6" placeholder="Enter the six-digit code" required /></label><PasswordField label="New password" name="password" autoComplete="new-password" minLength="8" /><small>8–128 characters, a letter and a number, no spaces.</small><PasswordField label="Confirm password" name="confirmPassword" autoComplete="new-password" minLength="8" /><button className="primary" disabled={busy}>{busy ? 'Updating…' : 'Update password'}</button></form>{pendingDevOtp && <div className="info-card"><b>Development-only code</b><p>{pendingDevOtp}</p></div>}{forgotResult && <p className="auth-switch">{forgotResult.message}</p>}{banner && <Banner banner={banner} />}</AuthCard>;

  const userNav = [['home', 'Overview'], ['scanner', 'Detector'], ['history', 'Scan History'], ['help', 'Recovery Guide'], ...(user?.isGuest ? [] : [['profile', 'Profile'], ['settings', 'Settings']]), ['about', 'About Us']];
  const adminNav = [['adminOverview', 'Control Center'], ['adminReports', 'Report Review'], ['adminSupport', 'Help Inbox'], ['adminUsers', 'Accounts'], ['adminAnalytics', 'System Analysis'], ['adminAudit', 'Audit Log'], ['adminCyber', 'CyberShield'], ['adminEvents', 'Simulate Event'], ['profile', 'My Profile'], ['settings', 'Security Settings']];
  let content = isAdmin ? <AdminOverview data={adminOverview} go={go} /> : <MemberOverview user={user} scanTotal={scanTotal} go={go} />;
  if (page === 'scanner' && !isAdmin) content = <ScannerPage key={user.id} scanMode={scanMode} setScanMode={setScanMode} message={message} setMessage={setMessage} imageFile={imageFile} setImageFile={setImageFile} ocrProgress={ocrProgress} analyze={analyze} analyzeImage={analyzeImage} analysis={analysis} clearAnalysis={() => setAnalysis(null)} busy={busy} />;
  if (page === 'history' && !isAdmin) content = <HistoryPage history={history} total={historyTotal} page={historyPage} pages={historyPages} level={historyLevel} setPage={setHistoryPage} setLevel={setHistoryLevel} openReport={(item) => { setSelectedReport(item); go('report'); }} deleteScan={deleteScan} />;
  if (page === 'report' && selectedReport) content = <><ReportDetail report={selectedReport} back={() => go(isAdmin ? 'adminReports' : 'history')} />{isAdmin && <AdminReportEditor report={selectedReport} save={saveAdminReport} busy={busy} />}</>;
  if (page === 'profile' && !user.isGuest) content = <ProfilePage user={user} scanTotal={scanTotal} saveProfile={saveProfile} busy={busy} />;
  if (page === 'settings' && !user.isGuest) content = <SettingsPage user={user} savePreferences={savePreferences} changePassword={changePassword} busy={busy} />;
  if (page === 'help') content = <HelpPage user={user} sendHelp={sendHelp} busy={busy} mySupport={mySupport} />;
  if (page === 'about') content = <AboutPage />;
  if (page === 'adminAnalytics' && isAdmin) content = <AdminAnalysis analytics={analytics} refresh={loadAnalytics} />;
  if (page === 'adminCyber' && isAdmin) content = <CyberDashboard dashboard={dashboard} refresh={loadDashboard} updateAlert={updateAlert} busy={busy} />;
  if (page === 'adminEvents' && isAdmin) content = <section><PageTitle tag="ADMIN CONSOLE" title="Simulate a security event">Creates clearly labelled synthetic data in MongoDB; it never touches real networks or devices.</PageTitle><EventForm event={event} setEvent={setEvent} busy={busy} submit={createEvent} /><button className="secondary page-action" onClick={seedDemo} disabled={busy}>Load safe demo data</button></section>;
  if (page === 'adminReports' && isAdmin) content = <AdminReports reports={adminReports} total={adminReportTotal} page={adminReportPage} pages={adminReportPages} level={adminReportLevel} setPage={setAdminReportPage} setLevel={setAdminReportLevel} openReport={(report) => { setSelectedReport(report); go('report'); }} />;
  if (page === 'adminAudit' && isAdmin) content = <AuditLogPage logs={auditLogs} />;
  if (page === 'adminSupport' && isAdmin) content = <AdminSupport items={supportInbox} busy={busy} updateStatus={updateSupportStatus} replyToHelp={replyToHelp} />;
  if (page === 'adminUsers' && isAdmin) content = <UserManagement users={users} busy={busy} onChange={manageUser} onDelete={removeUser} onDetails={openAccountDetails} />;
  if (page === 'adminAccountDetails' && isAdmin) content = <AccountDetails details={accountDetails} back={() => go('adminUsers')} openReport={(report) => { setSelectedReport(report); go('report'); }} />;
  const visibleNav = isAdmin ? adminNav : userNav;
  return <div className="app-shell"><div className="grid-bg" /><header className="topbar"><Brand onClick={() => go(isAdmin ? 'adminOverview' : 'home')} />{user && <nav>{visibleNav.slice(0, 4).map(([id, label]) => <button className={page === id ? 'active' : ''} key={id} onClick={() => go(id)}>{label}</button>)}</nav>}{user && <div className="header-status"><span className="status-dot" /> ENGINE ONLINE</div>}{user ? <div className="account-menu"><button onClick={() => go(isAdmin ? 'adminOverview' : user.isGuest ? 'scanner' : 'profile')}><b>{user.name}</b><small>{isAdmin ? 'ADMIN' : user.isGuest ? 'GUEST' : 'MEMBER'}</small></button><button className="signout" disabled={busy} onClick={logout}>{busy ? 'Signing out…' : 'Sign out'}</button></div> : <div className="header-actions"><button className="text-button" onClick={() => go('login')}>Sign in</button><button className="primary" onClick={() => go('register')}>Create account</button></div>}</header>{user ? <div className="layout"><aside className="sidebar"><span className="side-label">{isAdmin ? 'ADMIN ACCESS' : user.isGuest ? 'GUEST ACCESS' : 'MEMBER ACCESS'}</span>{visibleNav.map(([id, label]) => <button className={page === id ? 'active' : ''} key={id} onClick={() => go(id)}>{label}</button>)}</aside><main className="content">{banner && <Banner banner={banner} onClose={() => setBanner(null)} />}{content}</main></div> : <main className="landing-content">{banner && <Banner banner={banner} onClose={() => setBanner(null)} />}{<Landing go={go} guestLogin={guestLogin} busy={busy} />}</main>}</div>;
}
